package uz.horecaos.platform.pos.infrastructure.clopos;

/**
 * The configuration keys a Clopos installation carries, and the reason each one
 * is configuration rather than a secret.
 *
 * <p>Clopos's four authentication fields come from two different places, and the
 * split decides where each of them is stored.
 *
 * <ul>
 *   <li>{@link #INTEGRATOR_ID} identifies <em>HorecaOS</em> to Clopos. It is issued
 *       once, to us, and reused across every brand we connect to — a
 *       platform-level value rather than a tenant-level one, and not a secret.</li>
 *   <li>{@link #BRAND} and {@link #CLIENT_ID} are generated by the restaurant in
 *       their own back office. Both are identifiers.</li>
 *   <li>The client secret is the one credential, and it is not here. It lives
 *       behind the ADR 0028 reference on the installation.</li>
 * </ul>
 *
 * <p>There is no environment key. Clopos publishes one host for test and
 * production alike; the segregation lives entirely in whether the integrator and
 * the brand are both in test mode, and pairing them wrongly is answered with an
 * HTTP 200 whose body says {@code success: false}. So the environment dimension
 * collapses into which integrator id this installation carries.
 */
public final class CloposConfig {

    /** The Clopos brand slug. One installation is one brand. */
    public static final String BRAND = "clopos.brand";

    /** The restaurant's own Open API client identifier. Not a secret. */
    public static final String CLIENT_ID = "clopos.clientId";

    /** HorecaOS's integrator id. Platform-level, and the test/production dimension. */
    public static final String INTEGRATOR_ID = "clopos.integratorId";

    /**
     * The Clopos venue this binding points at, sent as the {@code x-venue} header.
     *
     * <p>Per binding rather than per installation, because Clopos authenticates
     * per brand and selects the venue per request. This is the single value that
     * decides which kitchen a customer's dinner is printed in.
     */
    public static final String VENUE_ID = "clopos.venueId";

    /**
     * The sale type to export orders under, as Clopos numbers them.
     *
     * <p>Read from configuration and never guessed. Clopos's sale types are
     * per-brand rows with free-text names — its own examples are Azerbaijani —
     * so nothing in the API lets an adapter infer which one means delivery.
     */
    public static final String SALE_TYPE_ID = "clopos.saleTypeId";

    /**
     * The currency every amount on this installation is in, asserted rather than
     * read.
     *
     * <p>Clopos has no currency field anywhere in its API — not on an order, a
     * product, a price list, a receipt, or a payment method. It is presumably a
     * brand-level back-office setting we cannot see, so it is stated here and the
     * export reconciles its total against the receipt on read-back.
     */
    public static final String CURRENCY = "clopos.currency";

    /**
     * Whether the till's clerk must accept an exported order.
     *
     * <p>Defaults to requiring the clerk, which is the safer posture and the
     * slower one. Clopos's {@code auto_order_accept} turns it from an authority
     * into a recipient for that order and, with auto-send to stations, prints the
     * ticket immediately. An order sitting in {@code PENDING} awaiting a clerk is
     * recoverable and visible; an order auto-accepted and auto-sent is already
     * food. The safe failure and the convenient configuration point in opposite
     * directions here, and the default takes the safe one.
     */
    public static final String REQUIRE_CLERK_APPROVAL = "clopos.requireClerkApproval";

    /**
     * Whether this installation has been observed to hand our correlation
     * reference back on a read.
     *
     * <p>False until somebody establishes otherwise against a real brand, and it
     * is the single flag that decides whether an uncertain export can resolve
     * without a person. Clopos's order responses carry {@code integration_uuid},
     * {@code integration_id} and {@code customer_ref_id}, all described as coming
     * from the integration source "if provided" — and its create request has no
     * documented field that provides any of them. The prose also documents an
     * {@code order_number} the OpenAPI schema omits. Sending it costs nothing and
     * the read-back is a five-minute experiment, so the flag exists to record the
     * answer rather than to assume one.
     */
    public static final String CORRELATION_ECHO_VERIFIED = "clopos.correlationEchoVerified";

    private CloposConfig() {
    }
}
