-- ADR 0011: POS installations, bindings, and capability adapters.
--
-- ADR 0026 (V0013) already owns the generic provider model — installations,
-- bindings, binding capabilities, entity mappings. None of that is repeated
-- here. What this migration adds is the two things ADR 0011 owns that the
-- generic model deliberately left open, and both of them exist because of
-- something Clopos actually does.
--
-- ---------------------------------------------------------------------------
-- One: capability is a property of the installation, not of the provider
-- ---------------------------------------------------------------------------
--
-- Clopos credentials are generated by the restaurant in their own back office,
-- and step three of that procedure is choosing which Staff user the integration
-- acts as. Every API call made with those credentials runs with that user's role
-- and permissions. Two restaurants on the same Clopos version can therefore
-- expose different surfaces to us because one picked a cashier and the other
-- picked an owner.
--
-- So a static per-provider capability table would be a lie about half the
-- estate, and a purely per-installation discovery would have nothing to check
-- the discovery against. This migration has both, and they answer different
-- questions:
--
--   integration.pos_provider_capabilities   what the provider's API can ever do
--   integration.pos_capability_probes       what this credential proved it can do
--   integration.installations.capability_snapshot  (ADR 0026) the current answer
--
-- The first is a ceiling. A probe can only ever narrow it, never widen it, and
-- the trigger at the end of this file makes that a database rule rather than an
-- application convention: a POS binding cannot enable a capability the provider
-- does not have, whatever the control plane sends.
--
-- That rule has one name on it. PREPARATION_STATUS is UNSUPPORTED for Clopos
-- and it is not a gap waiting to be filled. The only preparation-shaped field in
-- the whole Clopos API is Receipt.order_status, and that field is one *we* write
-- through PATCH /receipts/{id}; nothing in the API reports a kitchen's progress
-- back. Reading our own writes back and presenting them to a branch manager as
-- POS telemetry would be a screen that lies about where the food is. Refusing it
-- here means the failure arrives at configuration time, in the control plane,
-- addressed to somebody who can do something about it — which is the entire
-- argument for ADR 0011's discovery step.
--
-- ---------------------------------------------------------------------------
-- Two: an export whose outcome is unknown is a row, not a retry
-- ---------------------------------------------------------------------------
--
-- Clopos has no idempotency mechanism of any kind. No key, no header, no
-- documented repeat semantics, no dedupe window; its own retry guidance says to
-- "check the server state first to avoid duplicates" on non-idempotent requests,
-- which is Clopos telling us in writing that a repeated POST /orders is a second
-- kitchen ticket. The upstream timeout is eight seconds, so uncertain outcomes
-- are routine rather than exotic.
--
-- The recovery read that exists — list the day's orders and match on venue,
-- customer phone, creation time and line composition — cannot distinguish a
-- double export from a customer who genuinely ordered the same thing twice
-- ninety seconds apart. It is a heuristic, and a heuristic is not
-- reconciliation. So integration.pos_order_exports below is a durable state
-- machine whose UNCERTAIN state exits through a human, and
-- integration.pos_export_candidates holds what the read found as evidence for
-- that human rather than as an input to an automatic decision.
--
-- There is one exception and it is the one worth building for. Every Clopos
-- *order response* carries integration_uuid, integration_id and
-- integration_status, described as coming "from the integration source, if
-- provided" — but CreateOrderRequest contains none of them, and the prose-only
-- order_number field is absent from the OpenAPI schema. If a correlation value
-- we send comes back on the read, the match stops being a heuristic and becomes
-- our own identifier, and the resolution can be automatic. Whether it does is an
-- empirical question with a five-minute answer against the pilot brand, and
-- until somebody runs it the column below is false for every installation and
-- every uncertain export goes to a person.
--
-- ---------------------------------------------------------------------------
-- What is deliberately not created here
-- ---------------------------------------------------------------------------
--
-- No table for polling cadence. ADR 0030 owns configuration resolution, the
-- cadence has to scale with a brand's venue count against a fixed 300 requests
-- per minute per (integrator, brand) budget, and a second policy store beside
-- ADR 0030's is how two answers to one question start disagreeing.
--
-- No table for the Clopos token. It has a one-hour life and no refresh grant, so
-- it is cache state, and ADR 0033's shared runtime state is where it belongs —
-- in the database it would be a credential at rest that ADR 0028 says we do not
-- keep, refreshed by whichever pod noticed first.

-- ---------------------------------------------------------------------------
-- The provider capability ceiling
-- ---------------------------------------------------------------------------
--
-- Platform-owned reference data, like integration.provider_environments. A
-- tenant can never write it, because the question it answers is "what does this
-- vendor's API do", and no restaurant is in a position to change that answer.
CREATE TABLE integration.pos_provider_capabilities (
    provider_type varchar(64) NOT NULL,
    capability_code varchar(64) NOT NULL,

    -- SUPPORTED   the API does this, and an adapter implements it.
    -- PARTIAL     the API does part of this. The rationale must say which part,
    --             because a caller that treats PARTIAL as SUPPORTED will discover
    --             the missing half during service.
    -- UNSUPPORTED the API does not do this. Enabling it on a binding is refused.
    support_level varchar(16) NOT NULL,

    -- Prose, and required. A support level with no stated reason is an assertion
    -- somebody will later have to re-derive from vendor documentation that has
    -- changed since. This column is where the reasoning lives.
    rationale varchar(1000) NOT NULL,

    -- Where the level came from, so a stale entry is identifiable as stale.
    evidence_source varchar(255) NOT NULL,
    assessed_on date NOT NULL,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_pos_provider_capability PRIMARY KEY (provider_type, capability_code),
    CONSTRAINT ck_pos_provider_capability_level CHECK (
        support_level IN ('SUPPORTED', 'PARTIAL', 'UNSUPPORTED')
    )
);

COMMENT ON TABLE integration.pos_provider_capabilities IS
    'ADR 0011. The ceiling: what a POS vendor''s API can ever do. A per-installation probe narrows this and can never widen it.';

COMMENT ON COLUMN integration.pos_provider_capabilities.support_level IS
    'SUPPORTED, PARTIAL, or UNSUPPORTED. An UNSUPPORTED capability cannot be enabled on a binding; the trigger at the end of this migration refuses it.';

-- ---------------------------------------------------------------------------
-- What one credential actually proved
-- ---------------------------------------------------------------------------
--
-- Append-only evidence. ADR 0011 requires capability discovery against a
-- controlled provider call and a stored snapshot with evidence; the snapshot
-- lives on integration.installations.capability_snapshot, and this is the
-- working that produced it. Kept as history rather than overwritten because the
-- interesting question is usually "when did this stop working", and a single
-- mutable row cannot answer it.
CREATE TABLE integration.pos_capability_probes (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    installation_id uuid NOT NULL,
    capability_code varchar(64) NOT NULL,

    -- SUPPORTED     the probe call succeeded.
    -- UNSUPPORTED   the provider or this credential's Staff user refused it.
    -- UNVERIFIABLE  the probe could not be run — the provider was down, or the
    --               capability has no read-only call that proves it without a
    --               side effect. Distinct from UNSUPPORTED on purpose: "we could
    --               not tell" and "it does not work" lead to different actions,
    --               and collapsing them turns an outage into a capability
    --               regression somebody spends an afternoon on.
    probe_status varchar(16) NOT NULL,

    -- The provider's own answer, for a human reading this later. Never a body:
    -- a Clopos error message has been observed to echo request content, and
    -- ADR 0029 keeps customer data out of anything an operator can list.
    provider_status_code integer,
    provider_error_code varchar(128),
    evidence varchar(1000),

    adapter_version varchar(64) NOT NULL,
    probed_at timestamptz NOT NULL,

    CONSTRAINT fk_pos_probe_installation FOREIGN KEY (tenant_id, installation_id)
        REFERENCES integration.installations (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT ck_pos_probe_status CHECK (
        probe_status IN ('SUPPORTED', 'UNSUPPORTED', 'UNVERIFIABLE')
    )
);

CREATE INDEX ix_pos_probe_latest
    ON integration.pos_capability_probes (tenant_id, installation_id, capability_code, probed_at DESC);

COMMENT ON TABLE integration.pos_capability_probes IS
    'ADR 0011. Per-installation capability evidence. Clopos credentials act as a Staff user the restaurant chose, so capability varies by installation and must be discovered rather than assumed.';

COMMENT ON COLUMN integration.pos_capability_probes.probe_status IS
    'UNVERIFIABLE is not UNSUPPORTED. One means the provider said no; the other means we could not ask, usually because proving the capability would have had a side effect.';

-- ---------------------------------------------------------------------------
-- The order export
-- ---------------------------------------------------------------------------

CREATE TABLE integration.pos_order_exports (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    order_id uuid NOT NULL,
    binding_id uuid NOT NULL,
    installation_id uuid NOT NULL,

    -- PENDING            created, nothing on the wire yet.
    -- SENT               an attempt is in flight.
    -- ACCEPTED           the provider answered and named the order it created.
    -- REJECTED           the provider refused on business grounds. Terminal;
    --                    a repeat produces the same refusal.
    -- UNCERTAIN          the outcome is unknown. The recovery read may run, but
    --                    the export never re-sends from this state.
    -- AWAITING_OPERATOR  the read finished and could not decide. A person does.
    -- RESOLVED_LANDED    established, by echoed correlation or by a person, that
    --                    the order exists at the POS.
    -- RESOLVED_ABSENT    established that it does not. This is the only state a
    --                    further attempt may leave from.
    -- ABANDONED          a person decided this order will not be exported. The
    --                    branch takes it another way.
    state varchar(24) NOT NULL,

    attempt_count integer NOT NULL DEFAULT 0,

    -- What we put in the provider's own correlation slot. Clopos's prose
    -- documents order_number as a caller-supplied string of at most twenty
    -- characters; its OpenAPI schema omits the field entirely. We send it
    -- anyway, because if it is honoured the recovery read below becomes
    -- deterministic and if it is dropped we have lost nothing.
    correlation_reference varchar(20),

    external_order_id varchar(64),
    external_receipt_id varchar(64),

    -- A stable hash over the exported line composition — external product ids,
    -- quantities, and unit amounts, in a canonical order. The recovery read
    -- matches on this rather than on names, which the restaurant can edit in
    -- their back office between our export and our read.
    line_fingerprint varchar(64) NOT NULL,

    -- ADR 0029. The recovery read needs to match on the customer's phone, and a
    -- phone number is personal data that must not sit in an integration table an
    -- operator can list. The hash is enough to compare a candidate against, and
    -- is not enough to call anybody.
    customer_phone_hash varchar(64) NOT NULL,

    -- The venue the order was exported to, as the provider knows it. Copied from
    -- the binding at export time rather than resolved on read: a binding that is
    -- later repointed must not change which venue a historical export claims to
    -- have reached.
    external_venue_reference varchar(64) NOT NULL,

    requested_at timestamptz NOT NULL,
    first_sent_at timestamptz,
    settled_at timestamptz,

    last_error_code varchar(128),
    last_error varchar(1000),

    -- How the uncertainty ended, and who ended it.
    resolution_kind varchar(32),
    resolution_reason varchar(1000),
    resolved_by varchar(255),
    resolved_at timestamptz,

    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_pos_export_order FOREIGN KEY (order_id, tenant_id)
        REFERENCES ordering.orders (id, tenant_id),
    CONSTRAINT fk_pos_export_binding FOREIGN KEY (tenant_id, binding_id)
        REFERENCES integration.bindings (tenant_id, id),
    CONSTRAINT fk_pos_export_installation FOREIGN KEY (tenant_id, installation_id)
        REFERENCES integration.installations (tenant_id, id),

    -- The platform-side idempotency that the provider does not offer. One order
    -- has one export row, so a duplicated command, a redelivered event, and a
    -- retried HTTP call all converge on the same row and the same state machine
    -- instead of producing a second row that would happily send a second ticket.
    CONSTRAINT uq_pos_export_per_order UNIQUE (tenant_id, order_id),
    CONSTRAINT uq_pos_export_identity UNIQUE (id, tenant_id),

    CONSTRAINT ck_pos_export_state CHECK (state IN (
        'PENDING', 'SENT', 'ACCEPTED', 'REJECTED', 'UNCERTAIN',
        'AWAITING_OPERATOR', 'RESOLVED_LANDED', 'RESOLVED_ABSENT', 'ABANDONED')),
    CONSTRAINT ck_pos_export_attempts CHECK (attempt_count >= 0),
    CONSTRAINT ck_pos_export_version CHECK (version >= 0),
    CONSTRAINT ck_pos_export_resolution_kind CHECK (
        resolution_kind IS NULL OR resolution_kind IN (
            'CORRELATION_ECHOED', 'OPERATOR_CONFIRMED_LANDED',
            'OPERATOR_CONFIRMED_ABSENT', 'OPERATOR_ABANDONED')),
    -- Pair completeness stated as an equality of null-ness. The disjunctive form
    -- (both null OR both set) is the same claim written so that a single null
    -- satisfies neither branch and the CHECK evaluates to UNKNOWN, which
    -- PostgreSQL accepts.
    CONSTRAINT ck_pos_export_resolution_complete CHECK (
        (resolution_kind IS NULL) = (resolved_at IS NULL)
    ),
    -- A resolution that no principal signed is not evidence of anything. The
    -- automatic path names the adapter; the operator path names the person.
    CONSTRAINT ck_pos_export_resolution_attributed CHECK (
        (resolution_kind IS NULL) = (resolved_by IS NULL)
    ),
    -- Claiming an order landed without saying which order it is would leave the
    -- fiscal write-back and every later reconciliation with nothing to key on.
    CONSTRAINT ck_pos_export_landed_names_order CHECK (
        state NOT IN ('ACCEPTED', 'RESOLVED_LANDED') OR external_order_id IS NOT NULL
    ),
    -- Nothing can have been sent zero times and have a first-sent time, and
    -- nothing that was sent can have none.
    CONSTRAINT ck_pos_export_sent_at CHECK (
        (attempt_count = 0) = (first_sent_at IS NULL)
    )
);

CREATE INDEX ix_pos_export_open
    ON integration.pos_order_exports (tenant_id, state, requested_at)
    WHERE state IN ('PENDING', 'SENT', 'UNCERTAIN', 'AWAITING_OPERATOR', 'RESOLVED_ABSENT');

CREATE INDEX ix_pos_export_binding
    ON integration.pos_order_exports (tenant_id, binding_id, requested_at DESC);

COMMENT ON TABLE integration.pos_order_exports IS
    'ADR 0011. One row per order per POS. The uniqueness on (tenant_id, order_id) is the only idempotency in this integration: Clopos provides none.';

COMMENT ON COLUMN integration.pos_order_exports.state IS
    'UNCERTAIN and AWAITING_OPERATOR are not retry states. Nothing re-sends except from RESOLVED_ABSENT, which only a person or an echoed correlation reference can reach.';

COMMENT ON COLUMN integration.pos_order_exports.correlation_reference IS
    'Sent as the provider''s caller-supplied order reference. Clopos documents the field in prose and omits it from its schema, so it may be silently dropped; the design does not depend on it being honoured.';

COMMENT ON COLUMN integration.pos_order_exports.line_fingerprint IS
    'Canonical hash of exported lines. Matched against a candidate order''s composition, because names and prices are mutable in the provider''s back office and ids are not.';

COMMENT ON COLUMN integration.pos_order_exports.customer_phone_hash IS
    'ADR 0029. The recovery read matches on phone; this table therefore holds a hash and never the number.';

-- Every attempt on the wire, kept whatever it came to. Without this, an export
-- that eventually succeeded shows no trace of the two uncertain attempts before
-- it, and "did we send this twice" becomes unanswerable at exactly the moment
-- somebody needs the answer.
CREATE TABLE integration.pos_export_attempts (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    export_id uuid NOT NULL,
    attempt_number integer NOT NULL,

    -- The ADR 0007 classification, unchanged. UNCERTAIN is a first-class value
    -- here rather than a flavour of failure, because it is the only one whose
    -- correct next action is neither "retry" nor "give up".
    outcome_status varchar(16) NOT NULL,

    provider_status_code integer,
    provider_error_code varchar(128),
    detail varchar(1000),

    started_at timestamptz NOT NULL,
    finished_at timestamptz,

    CONSTRAINT fk_pos_export_attempt_export FOREIGN KEY (tenant_id, export_id)
        REFERENCES integration.pos_order_exports (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_pos_export_attempt_number UNIQUE (export_id, attempt_number),
    CONSTRAINT ck_pos_export_attempt_number CHECK (attempt_number >= 1),
    CONSTRAINT ck_pos_export_attempt_status CHECK (
        outcome_status IN ('SUCCESS', 'REJECTED', 'RETRYABLE', 'UNCERTAIN')
    )
);

COMMENT ON TABLE integration.pos_export_attempts IS
    'ADR 0011. Append-only record of what happened on the wire. The question this exists to answer is "how many kitchen tickets might this order have produced".';

-- What the recovery read found. Evidence for a decision, not the decision.
CREATE TABLE integration.pos_export_candidates (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    export_id uuid NOT NULL,

    external_order_id varchar(64) NOT NULL,
    external_status varchar(32),
    external_created_at timestamptz,

    -- Whether this candidate carried back the correlation reference we sent.
    -- This is the single field that decides whether the match is an identifier
    -- or a guess, and today it is false everywhere because Clopos's create
    -- request has no documented slot for one.
    correlation_echoed boolean NOT NULL DEFAULT false,

    phone_matches boolean NOT NULL,
    fingerprint_matches boolean NOT NULL,
    -- Seconds between our export request and the candidate's creation time. Kept
    -- as a number an operator can read rather than a boolean somebody chose a
    -- threshold for.
    time_delta_seconds integer,

    discovered_at timestamptz NOT NULL,
    discovered_by_attempt integer NOT NULL,

    CONSTRAINT fk_pos_export_candidate_export FOREIGN KEY (tenant_id, export_id)
        REFERENCES integration.pos_order_exports (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_pos_export_candidate UNIQUE (export_id, external_order_id),
    CONSTRAINT ck_pos_export_candidate_attempt CHECK (discovered_by_attempt >= 1)
);

CREATE INDEX ix_pos_export_candidate_export
    ON integration.pos_export_candidates (tenant_id, export_id);

COMMENT ON TABLE integration.pos_export_candidates IS
    'ADR 0011. Orders at the POS that could be the one we may or may not have sent. Two identical baskets from one phone ninety seconds apart are a customer who ordered twice and a double export, and nothing here can tell them apart.';

COMMENT ON COLUMN integration.pos_export_candidates.correlation_echoed IS
    'True only when the provider returned our own reference on the candidate. The one condition under which an uncertain export may resolve without a person.';

-- ---------------------------------------------------------------------------
-- The rule that makes an unsupported capability unconfigurable
-- ---------------------------------------------------------------------------
--
-- ADR 0011 requires that the control plane cannot make an unsupported capability
-- the sole business path. A control-plane check alone would be a rule held in
-- one screen; this holds it where every writer meets it, including a migration,
-- a fixture, and a support script at two in the morning.
--
-- Scoped to POS installations. integration.binding_capabilities is the generic
-- ADR 0026 table and carries delivery and payment capability codes too, and this
-- function must let every one of those through untouched.
CREATE OR REPLACE FUNCTION integration.pos_capability_is_supported()
RETURNS trigger AS $$
DECLARE
    installation_category text;
    installation_provider text;
    declared_support text;
BEGIN
    SELECT i.provider_category, i.provider_type
      INTO installation_category, installation_provider
      FROM integration.bindings b
      JOIN integration.installations i
        ON i.id = b.installation_id AND i.tenant_id = b.tenant_id
     WHERE b.id = NEW.binding_id AND b.tenant_id = NEW.tenant_id;

    IF installation_category IS DISTINCT FROM 'POS' THEN
        RETURN NEW;
    END IF;

    SELECT c.support_level
      INTO declared_support
      FROM integration.pos_provider_capabilities c
     WHERE c.provider_type = installation_provider
       AND c.capability_code = NEW.capability_code;

    IF declared_support IS NULL THEN
        -- Not a permissive default. A POS capability nobody has assessed is a
        -- capability nobody can say works, and enabling it would put a
        -- restaurant's orders behind an assumption.
        RAISE EXCEPTION
            'POS provider % has no assessed support for capability %; add it to integration.pos_provider_capabilities first',
            installation_provider, NEW.capability_code
            USING ERRCODE = 'check_violation';
    END IF;

    IF declared_support = 'UNSUPPORTED' AND NEW.enabled THEN
        RAISE EXCEPTION
            'POS provider % does not support capability %, so it cannot be enabled on a binding',
            installation_provider, NEW.capability_code
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_binding_capability_pos_support
    BEFORE INSERT OR UPDATE ON integration.binding_capabilities
    FOR EACH ROW EXECUTE FUNCTION integration.pos_capability_is_supported();

COMMENT ON FUNCTION integration.pos_capability_is_supported() IS
    'ADR 0011. Refuses a POS binding capability the provider does not have. Named for the question it answers rather than for the table it guards, because the answer is the point.';

-- ---------------------------------------------------------------------------
-- The Clopos assessment, and the fake it is proved against
-- ---------------------------------------------------------------------------
--
-- Read from the Clopos Open API v2 OpenAPI document and its 32 documentation
-- pages on 2026-08-23; the working is in docs/providers/clopos-api.md. Every
-- rationale below is a fact about the API rather than a judgement about the
-- vendor, so a future reader can check it against the same source.
INSERT INTO integration.pos_provider_capabilities
    (provider_type, capability_code, support_level, rationale, evidence_source, assessed_on)
VALUES
    ('clopos', 'CATALOG_READ', 'SUPPORTED',
     'GET /products, /categories, /price-lists, /price-lists/prices and /stations all read. Full re-read only: there is no updated_at filter, no date range, no cursor, no ETag and no change feed, so ADR 0012 stages a whole snapshot every run.',
     'clopos openapi.json; /api-reference/v2/products/get-all-products', DATE '2026-08-23'),

    ('clopos', 'AVAILABILITY_READ', 'PARTIAL',
     'GET /products/stop-list returns per-product stock limits with a per-row millisecond timestamp, which is the only incremental surface in the API. It is partial because per-venue availability lives in an undocumented product.venues array whose element shape appears in no schema and no example.',
     'clopos /api-reference/v2/products/get-stop-list; product.venues undocumented', DATE '2026-08-23'),

    ('clopos', 'ORDER_APPROVAL', 'PARTIAL',
     'A genuine authority: PENDING to RECEIVED is a clerk pressing a button on the POS terminal and we cannot make that transition. Partial because there are no webhooks, so the decision reaches us one poll interval late and a race with HorecaOS Operations is decided by our polling cadence rather than by who decided first.',
     'clopos /api-reference/v2/orders/get-orders; /webhooks.md', DATE '2026-08-23'),

    ('clopos', 'ORDER_EXPORT', 'SUPPORTED',
     'POST /orders creates the order. Supported, and carrying the largest risk on this integration: there is no idempotency key of any kind, so a repeated post is a second kitchen ticket with no documented way to detect the first.',
     'clopos /api-reference/v2/orders/create-order; /errors.md retry guidance', DATE '2026-08-23'),

    ('clopos', 'ORDER_CANCELLATION', 'PARTIAL',
     'PUT /orders/{id} with status IGNORE works while the order is still PENDING. Once a clerk accepts it a receipt exists and there is no documented order-level cancel; PATCH /receipts/{id} order_status CANCELLED sets a label and is not documented to void the receipt, reverse stock, or stop the kitchen.',
     'clopos /api-reference/v2/orders/update-order; /receipts/patch-update-receipt', DATE '2026-08-23'),

    ('clopos', 'PREPARATION_STATUS', 'UNSUPPORTED',
     'Nothing in the API reports a kitchen''s progress. The only preparation-shaped field, Receipt.order_status, is one of the four fields PATCH /receipts/{id} lets us write, and every other receipt field is explicitly read-only. Reading our own writes back would be telemetry we invented.',
     'clopos /api-reference/v2/receipts/patch-update-receipt', DATE '2026-08-23'),

    ('clopos', 'RECEIPT_READ', 'SUPPORTED',
     'GET /receipts, /receipts/{id} and /receipts/{id}/stock-operations read closed receipts and the stock movements they caused. Feeds ADR 0043 reporting; it is not a customer-facing path.',
     'clopos /api-reference/v2/receipts/get-receipts', DATE '2026-08-23'),

    ('clopos', 'FISCAL_IDENTIFIER_WRITE_BACK', 'SUPPORTED',
     'PATCH /receipts/{id} writes fiscal_id, and does so even after the receipt is closed. This is where ADR 0038 writes back the identifier the payment provider issued. Safe to retry: it sets one specific value and is idempotent by construction.',
     'clopos /api-reference/v2/receipts/patch-update-receipt', DATE '2026-08-23'),

    ('clopos', 'FULFILLMENT_STATUS_WRITE', 'SUPPORTED',
     'PATCH /receipts/{id} order_status. Outbound only, and the mirror image of PREPARATION_STATUS: we tell the restaurant where the order is. It must never be read back as though the kitchen had reported it.',
     'clopos /api-reference/v2/receipts/patch-update-receipt', DATE '2026-08-23'),

    ('clopos', 'CUSTOMER_UPSERT', 'PARTIAL',
     'POST /customers exists and CreateOrderRequest requires a customer id, so an export needs a Clopos customer first. Partial because there is no documented guest path, the create has the same absence of idempotency as the order create, and exporting a phone and address is an ADR 0029 personal-data flow that needs a consent basis rather than an endpoint.',
     'clopos /api-reference/v2/orders/create-order OrderCustomer schema', DATE '2026-08-23'),

    -- The ADR 0007 fake. It exists so the provider-neutral contract is proved
    -- against something whose failures can be commanded, and it deliberately
    -- supports everything Clopos does not — otherwise the abstraction would only
    -- ever have been exercised in the one shape Clopos happens to have.
    ('fake-pos', 'CATALOG_READ', 'SUPPORTED',
     'The controlled fake implements every capability, including the ones Clopos lacks, so the provider-neutral contract is tested against more than one shape.',
     'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'AVAILABILITY_READ', 'SUPPORTED',
     'See CATALOG_READ.', 'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'ORDER_APPROVAL', 'SUPPORTED',
     'See CATALOG_READ.', 'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'ORDER_EXPORT', 'SUPPORTED',
     'The fake honours an idempotency key, which is exactly what Clopos does not. That contrast is the point of having it.',
     'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'ORDER_CANCELLATION', 'SUPPORTED',
     'See CATALOG_READ.', 'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'PREPARATION_STATUS', 'SUPPORTED',
     'Supported here precisely because it is unsupported on Clopos: a capability that no adapter in the build implements is a capability whose refusal path is never exercised.',
     'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'RECEIPT_READ', 'SUPPORTED',
     'See CATALOG_READ.', 'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'FISCAL_IDENTIFIER_WRITE_BACK', 'SUPPORTED',
     'See CATALOG_READ.', 'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'FULFILLMENT_STATUS_WRITE', 'SUPPORTED',
     'See CATALOG_READ.', 'ADR 0007 controlled fake provider', DATE '2026-08-23'),
    ('fake-pos', 'CUSTOMER_UPSERT', 'SUPPORTED',
     'See CATALOG_READ.', 'ADR 0007 controlled fake provider', DATE '2026-08-23');

-- The one approved Clopos endpoint. There is no separate sandbox host: test
-- versus production is a property of the integrator credential and the brand,
-- not of the hostname, so the environment dimension moves into the
-- installation's non-sensitive configuration as the integrator id.
INSERT INTO integration.provider_environments
    (code, provider_category, provider_type, base_url, is_production, egress_allowlist, notes)
VALUES
    ('clopos-open-api-v2', 'POS', 'clopos', 'https://integrations.clopos.com/open-api/v2', true,
     'integrations.clopos.com',
     'The only documented host. Test and production integrators share it; segregation is in the credential pair, so a test integrator against a production brand returns 200 with success false.')
ON CONFLICT (code) DO NOTHING;

-- Repeated rather than assumed. V0013 created the integration schema's tables
-- without a grant block, and a table this migration grants on inside a schema
-- the role cannot enter is a permission that reads as present and is not.
GRANT USAGE ON SCHEMA integration TO horecaos_application;

GRANT SELECT ON integration.pos_provider_capabilities TO horecaos_application;
GRANT SELECT, INSERT ON integration.pos_capability_probes TO horecaos_application;
GRANT SELECT, INSERT, UPDATE ON integration.pos_order_exports TO horecaos_application;
-- No UPDATE and no DELETE. An attempt is what happened; editing one would make
-- the count of possible kitchen tickets negotiable after the fact.
GRANT SELECT, INSERT ON integration.pos_export_attempts TO horecaos_application;
-- DELETE is granted because a candidate is a working note from one recovery
-- read, superseded when the read runs again. It is not evidence of a decision;
-- the decision lives on the export row with the principal who made it.
GRANT SELECT, INSERT, DELETE ON integration.pos_export_candidates TO horecaos_application;
