#!/usr/bin/env python3
"""Generate HorecaOS's dependency-free TypeScript OpenAPI client contract.

The backend's running Springdoc response is the input. This generator emits
types and a transport interface only: browser authentication, retries and the
actual fetch implementation stay with each frontend, while request and response
shapes can never be hand-copied there.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


HTTP_METHODS = ("get", "put", "post", "delete", "patch", "head", "options", "trace")


def ts_property(name: str) -> str:
    return name if name.isidentifier() else json.dumps(name)


def reference_name(reference: str) -> str:
    prefix = "#/components/schemas/"
    if not reference.startswith(prefix):
        raise ValueError(f"Unsupported OpenAPI reference: {reference}")
    return reference.removeprefix(prefix)


def schema_type(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return reference_name(schema["$ref"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "oneOf" in schema:
        return " | ".join(schema_type(item) for item in schema["oneOf"])
    if "anyOf" in schema:
        return " | ".join(schema_type(item) for item in schema["anyOf"])
    if "allOf" in schema:
        return " & ".join(schema_type(item) for item in schema["allOf"])
    kind = schema.get("type")
    nullable = " | null" if schema.get("nullable") else ""
    if kind == "array":
        return f"Array<{schema_type(schema.get('items'))}>{nullable}"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        members = [
            f"{ts_property(name)}{' ' if name in required else '? '}: {schema_type(value)}"
            for name, value in sorted(properties.items())
        ]
        additional = schema.get("additionalProperties")
        if additional:
            members.append(f"[key: string]: {schema_type(additional if isinstance(additional, dict) else {})}")
        return "{ " + "; ".join(members) + " }" + nullable
    primitive = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")
    return primitive + nullable


def media_schema(content: dict[str, Any] | None) -> dict[str, Any] | None:
    if not content:
        return None
    json_content = content.get("application/json")
    if json_content:
        return json_content.get("schema")
    return next(iter(content.values())).get("schema")


def parameters_type(parameters: list[dict[str, Any]]) -> str:
    by_location: dict[str, list[dict[str, Any]]] = {}
    for parameter in parameters:
        by_location.setdefault(parameter.get("in", "query"), []).append(parameter)
    if not by_location:
        return "Record<string, never>"
    locations = []
    for location, values in sorted(by_location.items()):
        fields = []
        for parameter in sorted(values, key=lambda item: item.get("name", "")):
            optional = "" if parameter.get("required") else "?"
            fields.append(
                f"{ts_property(parameter['name'])}{optional}: {schema_type(parameter.get('schema'))}")
        locations.append(f"{ts_property(location)}: {{ {'; '.join(fields)} }}")
    return "{ " + "; ".join(locations) + " }"


def operation_type(path: str, method: str, operation: dict[str, Any]) -> str:
    parameters = operation.get("parameters", [])
    request_body = operation.get("requestBody")
    request_fields = [f"parameters: {parameters_type(parameters)}"]
    if request_body:
        optional = "" if request_body.get("required") else "?"
        request_fields.append(
            f"body{optional}: {schema_type(media_schema(request_body.get('content')))}")
    responses = []
    for status, response in sorted(operation.get("responses", {}).items()):
        responses.append(f"{json.dumps(status)}: {schema_type(media_schema(response.get('content')))}")
    return (
        "{ "
        f"method: {json.dumps(method.upper())}; path: {json.dumps(path)}; "
        f"request: {{ {'; '.join(request_fields)} }}; "
        f"responses: {{ {'; '.join(responses) if responses else '[status: string]: unknown'} }}"
        " }"
    )


def render(document: dict[str, Any]) -> str:
    schemas = document.get("components", {}).get("schemas", {})
    lines = [
        "/*",
        " * GENERATED FILE — do not edit by hand.",
        " * Source: api/openapi/v1/horecaos-api.json, generated by tools/openapi/generate_types.py.",
        " * Update with: make openapi-baseline",
        " */",
        "",
        "export type ApiProblem = {",
        "  type?: string; title?: string; status?: number; detail?: string; instance?: string;",
        "  code?: string; correlationId?: string; errors?: Array<{ field?: string; code?: string }>;",
        "};",
        "",
    ]
    for name, schema in sorted(schemas.items()):
        if schema.get("type") == "object" or "properties" in schema:
            required = set(schema.get("required", []))
            lines.append(f"export interface {name} {{")
            for property_name, property_schema in sorted(schema.get("properties", {}).items()):
                optional = "" if property_name in required else "?"
                lines.append(f"  {ts_property(property_name)}{optional}: {schema_type(property_schema)};")
            additional = schema.get("additionalProperties")
            if additional:
                lines.append(
                    "  [key: string]: "
                    + schema_type(additional if isinstance(additional, dict) else {})
                    + ";")
            lines.append("}")
        else:
            lines.append(f"export type {name} = {schema_type(schema)};")
        lines.append("")

    lines.extend(["export interface Operations {"])
    for path, methods in sorted(document.get("paths", {}).items()):
        for method, operation in sorted(methods.items()):
            if method not in HTTP_METHODS:
                continue
            name = operation.get("operationId", f"{method}_{path}")
            lines.append(f"  {json.dumps(name)}: {operation_type(path, method, operation)};")
    lines.extend([
        "}",
        "",
        "export type OperationName = keyof Operations;",
        "export type OperationRequest<Name extends OperationName> = Operations[Name]['request'];",
        "export type OperationResponse<Name extends OperationName> = {",
        "  [Status in keyof Operations[Name]['responses']]: {",
        "    status: Status; body: Operations[Name]['responses'][Status];",
        "  }",
        "}[keyof Operations[Name]['responses']];",
        "",
        "/** Frontends provide their own authenticated transport; this interface keeps every call typed. */",
        "export interface HorecaOSApiClient {",
        "  request<Name extends OperationName>(",
        "    operation: Name, request: OperationRequest<Name>,",
        "  ): Promise<OperationResponse<Name>>;",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    document = json.loads(args.input.read_text(encoding="utf-8"))
    output = render(document)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
