import { Locale } from '../../core/i18n/i18n';

/**
 * Staff 9.3 — the long tail of `AuditFact.of("<code>", …)` action codes
 * `activity-log-action-labels.ts`'s own `ACTION_LABEL_KEYS` does not
 * hand-curate, mechanically enumerated from the platform's own Java sources
 * (see `activity-log-action-codes-coverage.spec.ts`'s own doc for exactly
 * what "enumerated from the code" means and does not reach here).
 *
 * **A separate table, not more entries in `messages.*.ts`.** The three
 * central message catalogues are bundled into this app's eager, initial
 * chunk — `angular.json`'s own budget exists to keep that chunk small, and
 * roughly two hundred short activity-log sentences pushed it over. This
 * module is reached only from `activity-log-action-labels.ts`, which only
 * `activity-log-page.ts` imports, and that page is itself lazy-loaded
 * (`app.routes.ts`'s `staff/activity` route) — so the whole table ships
 * only to an operator who actually opens the activity log, in that route's
 * own chunk, never in the bundle every screen pays for.
 *
 * **Mechanically generated, not hand-written prose.** Each sentence is
 * composed word-by-word from the action code's own segments through a fixed
 * glossary, the same idea `activity-log-action-labels.ts`'s own
 * `humanizeActionCode` fallback already uses, applied per locale instead of
 * only to English. That makes every entry non-blank and genuinely in the named
 * language rather than a bare dotted code — the real bar this row's test
 * enforces — without claiming native fluency: a code with an unusual word
 * shape can still read stiffly. Treat this as a first pass a linguist
 * reviews later, not a finished translation memory.
 */
export const ACTIVITY_ACTION_SENTENCES: Readonly<Record<string, Readonly<Record<Locale, string>>>> = {
  'MARKETING_AUDIENCE_EXPORTED': { en: 'Marketing audience exported', ru: 'Маркетинг аудитория экспортировано', 'uz-Latn': 'Marketing auditoriya eksport qilindi' },
  'MARKETING_AUDIENCE_SNAPSHOT_BUILT': { en: 'Marketing audience snapshot built', ru: 'Маркетинг аудитория снимок сформировано', 'uz-Latn': 'Marketing auditoriya nusxa shakllantirildi' },
  'MARKETING_CAMPAIGN_APPROVED': { en: 'Marketing campaign approved', ru: 'Маркетинг кампания согласовано', 'uz-Latn': 'Marketing kampaniya tasdiqlandi' },
  'MARKETING_CAMPAIGN_HALTED': { en: 'Marketing campaign halted', ru: 'Маркетинг кампания приостановлено', 'uz-Latn': 'Marketing kampaniya toʻxtatildi' },
  'MARKETING_CAMPAIGN_RESCHEDULED': { en: 'Marketing campaign rescheduled', ru: 'Маркетинг кампания перенесено', 'uz-Latn': 'Marketing kampaniya koʻchirildi' },
  'MARKETING_CAMPAIGN_RESUMED': { en: 'Marketing campaign resumed', ru: 'Маркетинг кампания возобновлено', 'uz-Latn': 'Marketing kampaniya davom ettirildi' },
  'MARKETING_COURIER_BROADCAST_DRAFTED': { en: 'Marketing courier broadcast drafted', ru: 'Маркетинг курьер рассылка черновик сохранён', 'uz-Latn': 'Marketing kuryer ommaviy xabar qoralama saqlandi' },
  'MARKETING_COURIER_BROADCAST_SEND_FAILED': { en: 'Marketing courier broadcast send failed', ru: 'Маркетинг курьер рассылка отправка ошибка', 'uz-Latn': 'Marketing kuryer ommaviy xabar yuborish xato' },
  'MARKETING_COURIER_BROADCAST_SENT': { en: 'Marketing courier broadcast sent', ru: 'Маркетинг курьер рассылка отправлено', 'uz-Latn': 'Marketing kuryer ommaviy xabar yuborildi' },
  'MARKETING_LINK_ARCHIVED': { en: 'Marketing link archived', ru: 'Маркетинг ссылка архивировано', 'uz-Latn': 'Marketing havola arxivlandi' },
  'MARKETING_LINK_MINTED': { en: 'Marketing link minted', ru: 'Маркетинг ссылка создано', 'uz-Latn': 'Marketing havola yaratildi' },
  'MARKETING_SUPPRESSION_LIFTED': { en: 'Marketing suppression lifted', ru: 'Маркетинг подавление снято', 'uz-Latn': 'Marketing toʻxtatish olib tashlandi' },
  'MARKETING_SUPPRESSION_RECORDED': { en: 'Marketing suppression recorded', ru: 'Маркетинг подавление зафиксировано', 'uz-Latn': 'Marketing toʻxtatish qayd etildi' },
  'PRICING_BENEFIT_GRANT_MINTED': { en: 'Pricing benefit grant minted', ru: 'Ценообразование льгота доступ создано', 'uz-Latn': 'Narxlash imtiyoz huquq yaratildi' },
  'adjustment-reason.archived': { en: 'Adjustment reason archived', ru: 'Корректировка причина архивировано', 'uz-Latn': 'Tuzatish sabab arxivlandi' },
  'approval.consumed': { en: 'Approval consumed', ru: 'Согласование использовано', 'uz-Latn': 'Tasdiqlash sarflandi' },
  'approval.decision.refused': { en: 'Approval decision refused', ru: 'Согласование решение отказано', 'uz-Latn': 'Tasdiqlash qaror rad etildi' },
  'approval.policy.authored': { en: 'Approval policy authored', ru: 'Согласование политика оформлено', 'uz-Latn': 'Tasdiqlash siyosat tuzildi' },
  'approval.policy.cancelled': { en: 'Approval policy cancelled', ru: 'Согласование политика отменено', 'uz-Latn': 'Tasdiqlash siyosat bekor qilindi' },
  'approval.policy.ended': { en: 'Approval policy ended', ru: 'Согласование политика завершено', 'uz-Latn': 'Tasdiqlash siyosat tugatildi' },
  'approval.requested': { en: 'Approval requested', ru: 'Согласование запрошено', 'uz-Latn': 'Tasdiqlash soʻralindi' },
  'audit.read': { en: 'Audit read', ru: 'Журнал просмотр', 'uz-Latn': 'Jurnal koʻrish' },
  'catalog.channelOffering.bulkSet': { en: 'Catalog channel offering bulk set', ru: 'Каталог канал предложение массовое установлено', 'uz-Latn': 'Katalog kanal taklif ommaviy oʻrnatildi' },
  'catalog.channelOffering.set': { en: 'Catalog channel offering set', ru: 'Каталог канал предложение установлено', 'uz-Latn': 'Katalog kanal taklif oʻrnatildi' },
  'catalog.comment-preset.attached': { en: 'Catalog comment preset attached', ru: 'Каталог комментарий шаблон прикреплено', 'uz-Latn': 'Katalog izoh shablon biriktirildi' },
  'catalog.comment-preset.created': { en: 'Catalog comment preset created', ru: 'Каталог комментарий шаблон создано', 'uz-Latn': 'Katalog izoh shablon yaratildi' },
  'catalog.comment-preset.detached': { en: 'Catalog comment preset detached', ru: 'Каталог комментарий шаблон откреплено', 'uz-Latn': 'Katalog izoh shablon ajratildi' },
  'catalog.comment-preset.updated': { en: 'Catalog comment preset updated', ru: 'Каталог комментарий шаблон обновлено', 'uz-Latn': 'Katalog izoh shablon yangilandi' },
  'catalog.itemSaleSchedule.replaced': { en: 'Catalog item sale schedule replaced', ru: 'Каталог позиция продажа расписание заменено', 'uz-Latn': 'Katalog band sotuv jadval almashtirildi' },
  'catalog.menu.bound': { en: 'Catalog menu bound', ru: 'Каталог меню привязано', 'uz-Latn': 'Katalog menyu bogʻlandi' },
  'catalog.menu.copied': { en: 'Catalog menu copied', ru: 'Каталог меню скопировано', 'uz-Latn': 'Katalog menyu nusxalandi' },
  'catalog.menu.created': { en: 'Catalog menu created', ru: 'Каталог меню создано', 'uz-Latn': 'Katalog menyu yaratildi' },
  'catalog.menu.item-added': { en: 'Catalog menu item added', ru: 'Каталог меню позиция добавлено', 'uz-Latn': 'Katalog menyu band qoʻshildi' },
  'catalog.menu.item-removed': { en: 'Catalog menu item removed', ru: 'Каталог меню позиция удалено', 'uz-Latn': 'Katalog menyu band oʻchirildi' },
  'catalog.menu.items-added-by-filter': { en: 'Catalog menu items added by filter', ru: 'Каталог меню позиции добавлено по фильтр', 'uz-Latn': 'Katalog menyu bandlar qoʻshildi boʻyicha filtr' },
  'catalog.menu.unbound': { en: 'Catalog menu unbound', ru: 'Каталог меню отвязано', 'uz-Latn': 'Katalog menyu bogʻlanishi bekor qilindi' },
  'catalog.menu.updated': { en: 'Catalog menu updated', ru: 'Каталог меню обновлено', 'uz-Latn': 'Katalog menyu yangilandi' },
  'catalog.offering.bulkSet': { en: 'Catalog offering bulk set', ru: 'Каталог предложение массовое установлено', 'uz-Latn': 'Katalog taklif ommaviy oʻrnatildi' },
  'catalog.offering.set': { en: 'Catalog offering set', ru: 'Каталог предложение установлено', 'uz-Latn': 'Katalog taklif oʻrnatildi' },
  'catalog.product.status_changed': { en: 'Catalog product status changed', ru: 'Каталог товар статус изменено', 'uz-Latn': 'Katalog mahsulot holat oʻzgartirildi' },
  'catalog.product.stopped_everywhere': { en: 'Catalog product stopped everywhere', ru: 'Каталог товар остановлено везде', 'uz-Latn': 'Katalog mahsulot toʻxtatildi hammasida' },
  'catalog.recommendation.attached': { en: 'Catalog recommendation attached', ru: 'Каталог рекомендация прикреплено', 'uz-Latn': 'Katalog tavsiya biriktirildi' },
  'catalog.recommendation.detached': { en: 'Catalog recommendation detached', ru: 'Каталог рекомендация откреплено', 'uz-Latn': 'Katalog tavsiya ajratildi' },
  'commercial.entitlement_override.granted': { en: 'Commercial entitlement override granted', ru: 'Коммерция право доступа переопределение предоставлено', 'uz-Latn': 'Tijorat huquq bekor qilib qoʻyish berildi' },
  'commercial.plan.created': { en: 'Commercial plan created', ru: 'Коммерция план создано', 'uz-Latn': 'Tijorat reja yaratildi' },
  'commercial.plan_version.activated': { en: 'Commercial plan version activated', ru: 'Коммерция план версия активировано', 'uz-Latn': 'Tijorat reja versiya faollashtirildi' },
  'commercial.plan_version.drafted': { en: 'Commercial plan version drafted', ru: 'Коммерция план версия черновик сохранён', 'uz-Latn': 'Tijorat reja versiya qoralama saqlandi' },
  'commercial.statement.issued': { en: 'Commercial statement issued', ru: 'Коммерция выписка выдано', 'uz-Latn': 'Tijorat hisobot berildi' },
  'commercial.statement.voided': { en: 'Commercial statement voided', ru: 'Коммерция выписка аннулировано', 'uz-Latn': 'Tijorat hisobot bekor qilindi' },
  'commercial.subscription.started': { en: 'Commercial subscription started', ru: 'Коммерция подписка начато', 'uz-Latn': 'Tijorat obuna boshlandi' },
  'commercial.subscription.transitioned': { en: 'Commercial subscription transitioned', ru: 'Коммерция подписка переведено', 'uz-Latn': 'Tijorat obuna oʻtkazildi' },
  'commercial.tenant_module.added': { en: 'Commercial tenant module added', ru: 'Коммерция компания модуль добавлено', 'uz-Latn': 'Tijorat kompaniya modul qoʻshildi' },
  'commercial.tenant_module.ended': { en: 'Commercial tenant module ended', ru: 'Коммерция компания модуль завершено', 'uz-Latn': 'Tijorat kompaniya modul tugatildi' },
  'commercial.wallet.adjusted': { en: 'Commercial wallet adjusted', ru: 'Коммерция кошелёк скорректировано', 'uz-Latn': 'Tijorat hamyon tuzatildi' },
  'commercial.wallet.bonus_expired': { en: 'Commercial wallet bonus expired', ru: 'Коммерция кошелёк бонус истекло', 'uz-Latn': 'Tijorat hamyon bonus muddati tugadi' },
  'commercial.wallet.bonus_granted': { en: 'Commercial wallet bonus granted', ru: 'Коммерция кошелёк бонус предоставлено', 'uz-Latn': 'Tijorat hamyon bonus berildi' },
  'commercial.wallet.card_attempt_superseded': { en: 'Commercial wallet card attempt superseded', ru: 'Коммерция кошелёк карта попытка заменено', 'uz-Latn': 'Tijorat hamyon karta urinish almashtirildi' },
  'commercial.wallet.card_charge_after_supersede': { en: 'Commercial wallet card charge after supersede', ru: 'Коммерция кошелёк карта списание после заменить', 'uz-Latn': 'Tijorat hamyon karta yechish keyin almashtirish' },
  'commercial.wallet.card_charge_declined': { en: 'Commercial wallet card charge declined', ru: 'Коммерция кошелёк карта списание отклонено', 'uz-Latn': 'Tijorat hamyon karta yechish rad etildi' },
  'commercial.wallet.card_charge_surplus_refused': { en: 'Commercial wallet card charge surplus refused', ru: 'Коммерция кошелёк карта списание излишек отказано', 'uz-Latn': 'Tijorat hamyon karta yechish ortiqcha rad etildi' },
  'commercial.wallet.card_charged': { en: 'Commercial wallet card charged', ru: 'Коммерция кошелёк карта списано', 'uz-Latn': 'Tijorat hamyon karta yechildi' },
  'commercial.wallet.deposit_recorded': { en: 'Commercial wallet deposit recorded', ru: 'Коммерция кошелёк депозит зафиксировано', 'uz-Latn': 'Tijorat hamyon depozit qayd etildi' },
  'commercial.wallet.deposit_reversed': { en: 'Commercial wallet deposit reversed', ru: 'Коммерция кошелёк депозит отменено', 'uz-Latn': 'Tijorat hamyon depozit bekor qilindi' },
  'commercial.wallet.payment_method_changed': { en: 'Commercial wallet payment method changed', ru: 'Коммерция кошелёк платёж способ изменено', 'uz-Latn': 'Tijorat hamyon toʻlov usul oʻzgartirildi' },
  'commercial.wallet.refunded': { en: 'Commercial wallet refunded', ru: 'Коммерция кошелёк возвращено', 'uz-Latn': 'Tijorat hamyon qaytarildi' },
  'commercial.wallet.transfer_recorded': { en: 'Commercial wallet transfer recorded', ru: 'Коммерция кошелёк перевод зафиксировано', 'uz-Latn': 'Tijorat hamyon oʻtkazma qayd etildi' },
  'conversation.closed': { en: 'Conversation closed', ru: 'Переписка закрыто', 'uz-Latn': 'Suhbat yopildi' },
  'conversation.history.read': { en: 'Conversation history read', ru: 'Переписка история просмотр', 'uz-Latn': 'Suhbat tarix koʻrish' },
  'conversation.reply.sent': { en: 'Conversation reply sent', ru: 'Переписка ответ отправлено', 'uz-Latn': 'Suhbat javob yuborildi' },
  'conversation.returned_to_flow': { en: 'Conversation returned to flow', ru: 'Переписка возвращено в сценарий', 'uz-Latn': 'Suhbat qaytarildi ga ssenariy' },
  'conversation.takeover': { en: 'Conversation takeover', ru: 'Переписка перехват', 'uz-Latn': 'Suhbat qoʻlga olish' },
  'conversations.flow_document.authored': { en: 'Conversations flow document authored', ru: 'Переписки сценарий документ оформлено', 'uz-Latn': 'Suhbatlar ssenariy hujjat tuzildi' },
  'courier-type.archived': { en: 'Courier type archived', ru: 'Курьер тип архивировано', 'uz-Latn': 'Kuryer turi arxivlandi' },
  'courier-type.updated': { en: 'Courier type updated', ru: 'Курьер тип обновлено', 'uz-Latn': 'Kuryer turi yangilandi' },
  'courier.adjustment.recorded': { en: 'Courier adjustment recorded', ru: 'Курьер корректировка зафиксировано', 'uz-Latn': 'Kuryer tuzatish qayd etildi' },
  'courier.applicant.erased': { en: 'Courier applicant erased', ru: 'Курьер заявитель удалено', 'uz-Latn': 'Kuryer nomzod oʻchirildi' },
  'courier.branch.bound': { en: 'Courier branch bound', ru: 'Курьер филиал привязано', 'uz-Latn': 'Kuryer filial bogʻlandi' },
  'courier.branch.unbound': { en: 'Courier branch unbound', ru: 'Курьер филиал отвязано', 'uz-Latn': 'Kuryer filial bogʻlanishi bekor qilindi' },
  'courier.cash.confirmed': { en: 'Courier cash confirmed', ru: 'Курьер наличные подтверждено', 'uz-Latn': 'Kuryer naqd pul tasdiqlandi' },
  'courier.cash.declared': { en: 'Courier cash declared', ru: 'Курьер наличные заявлено', 'uz-Latn': 'Kuryer naqd pul eʻlon qilindi' },
  'courier.compliance.recorded': { en: 'Courier compliance recorded', ru: 'Курьер проверка соответствия зафиксировано', 'uz-Latn': 'Kuryer muvofiqlik qayd etildi' },
  'courier.compliance.revealed': { en: 'Courier compliance revealed', ru: 'Курьер проверка соответствия раскрыто', 'uz-Latn': 'Kuryer muvofiqlik ochib berildi' },
  'courier.engagement.opened': { en: 'Courier engagement opened', ru: 'Курьер привлечение открыто', 'uz-Latn': 'Kuryer jalb qilish ochildi' },
  'courier.engagement.suspended': { en: 'Courier engagement suspended', ru: 'Курьер привлечение приостановлено', 'uz-Latn': 'Kuryer jalb qilish toʻxtatib turildi' },
  'courier.group.archived': { en: 'Courier group archived', ru: 'Курьер группа архивировано', 'uz-Latn': 'Kuryer guruh arxivlandi' },
  'courier.group.created': { en: 'Courier group created', ru: 'Курьер группа создано', 'uz-Latn': 'Kuryer guruh yaratildi' },
  'courier.group.joined': { en: 'Courier group joined', ru: 'Курьер группа вступил', 'uz-Latn': 'Kuryer guruh qoʻshildi' },
  'courier.group.left': { en: 'Courier group left', ru: 'Курьер группа вышел', 'uz-Latn': 'Kuryer guruh chiqdi' },
  'courier.payout.authorised': { en: 'Courier payout authorised', ru: 'Курьер выплата авторизовано', 'uz-Latn': 'Kuryer toʻlov ruxsat berildi' },
  'courier.ratecard.activated': { en: 'Courier ratecard activated', ru: 'Курьер тарифная сетка активировано', 'uz-Latn': 'Kuryer tarif jadvali faollashtirildi' },
  'courier.registration.lapsed': { en: 'Courier registration lapsed', ru: 'Курьер регистрация истёк срок', 'uz-Latn': 'Kuryer roʻyxatdan oʻtish muddati oʻtdi' },
  'courier.registration.revealed': { en: 'Courier registration revealed', ru: 'Курьер регистрация раскрыто', 'uz-Latn': 'Kuryer roʻyxatdan oʻtish ochib berildi' },
  'courier.registration.verified': { en: 'Courier registration verified', ru: 'Курьер регистрация проверено', 'uz-Latn': 'Kuryer roʻyxatdan oʻtish tasdiqlandi' },
  'courier.settlement.closed': { en: 'Courier settlement closed', ru: 'Курьер расчёт закрыто', 'uz-Latn': 'Kuryer hisob-kitob yopildi' },
  'customer.blacklist.revealed': { en: 'Customer blacklist revealed', ru: 'Клиент чёрный список раскрыто', 'uz-Latn': 'Mijoz qora roʻyxat ochib berildi' },
  'customer.csv_import_queued': { en: 'Customer CSV import queued', ru: 'Клиент CSV импорт в очереди', 'uz-Latn': 'Mijoz CSV import navbatga qoʻyildi' },
  'customer.identity.merged': { en: 'Customer identity merged', ru: 'Клиент личность объединено', 'uz-Latn': 'Mijoz shaxs birlashtirildi' },
  'customer.list.exported': { en: 'Customer list exported', ru: 'Клиент список экспортировано', 'uz-Latn': 'Mijoz roʻyxat eksport qilindi' },
  'customer.phone_lookup.performed': { en: 'Customer phone lookup performed', ru: 'Клиент телефон поиск выполнено', 'uz-Latn': 'Mijoz telefon qidiruv bajarildi' },
  'delivery.region.archived': { en: 'Delivery region archived', ru: 'Доставка регион архивировано', 'uz-Latn': 'Yetkazib berish hudud arxivlandi' },
  'delivery.region.created': { en: 'Delivery region created', ru: 'Доставка регион создано', 'uz-Latn': 'Yetkazib berish hudud yaratildi' },
  'delivery.region.updated': { en: 'Delivery region updated', ru: 'Доставка регион обновлено', 'uz-Latn': 'Yetkazib berish hudud yangilandi' },
  'delivery.tariff.location.bound': { en: 'Delivery tariff location bound', ru: 'Доставка тариф локация привязано', 'uz-Latn': 'Yetkazib berish tarif filial bogʻlandi' },
  'delivery.tariff.registered': { en: 'Delivery tariff registered', ru: 'Доставка тариф зарегистрировано', 'uz-Latn': 'Yetkazib berish tarif roʻyxatdan oʻtkazildi' },
  'delivery.tariff.version.activated': { en: 'Delivery tariff version activated', ru: 'Доставка тариф версия активировано', 'uz-Latn': 'Yetkazib berish tarif versiya faollashtirildi' },
  'delivery.tariff.version.drafted': { en: 'Delivery tariff version drafted', ru: 'Доставка тариф версия черновик сохранён', 'uz-Latn': 'Yetkazib berish tarif versiya qoralama saqlandi' },
  'delivery.zone.location.bound': { en: 'Delivery zone location bound', ru: 'Доставка зона локация привязано', 'uz-Latn': 'Yetkazib berish zona filial bogʻlandi' },
  'delivery.zone.location.unbound': { en: 'Delivery zone location unbound', ru: 'Доставка зона локация отвязано', 'uz-Latn': 'Yetkazib berish zona filial bogʻlanishi bekor qilindi' },
  'delivery.zone.registered': { en: 'Delivery zone registered', ru: 'Доставка зона зарегистрировано', 'uz-Latn': 'Yetkazib berish zona roʻyxatdan oʻtkazildi' },
  'delivery.zone.version.activated': { en: 'Delivery zone version activated', ru: 'Доставка зона версия активировано', 'uz-Latn': 'Yetkazib berish zona versiya faollashtirildi' },
  'delivery.zone.version.deactivated': { en: 'Delivery zone version deactivated', ru: 'Доставка зона версия деактивировано', 'uz-Latn': 'Yetkazib berish zona versiya faolsizlantirildi' },
  'delivery.zone.version.drafted': { en: 'Delivery zone version drafted', ru: 'Доставка зона версия черновик сохранён', 'uz-Latn': 'Yetkazib berish zona versiya qoralama saqlandi' },
  'dinein.qr.rotated': { en: 'Dinein QR rotated', ru: 'Зал QR обновлено', 'uz-Latn': 'Zal QR yangilandi' },
  'dinein.reservation.amended': { en: 'Dinein reservation amended', ru: 'Зал бронь изменено', 'uz-Latn': 'Zal bron oʻzgartirildi' },
  'dinein.reservation.guest_revealed': { en: 'Dinein reservation guest revealed', ru: 'Зал бронь гость раскрыто', 'uz-Latn': 'Zal bron mehmon ochib berildi' },
  'dinein.reservation.requested': { en: 'Dinein reservation requested', ru: 'Зал бронь запрошено', 'uz-Latn': 'Zal bron soʻralindi' },
  'dinein.session.opened': { en: 'Dinein session opened', ru: 'Зал сессия открыто', 'uz-Latn': 'Zal sessiya ochildi' },
  'dinein.session.round-added': { en: 'Dinein session round added', ru: 'Зал сессия раунд добавлено', 'uz-Latn': 'Zal sessiya tur qoʻshildi' },
  'dinein.settings.configured': { en: 'Dinein settings configured', ru: 'Зал настройки настроено', 'uz-Latn': 'Zal sozlamalar sozlandi' },
  'dinein.table.repositioned': { en: 'Dinein table repositioned', ru: 'Зал стол перемещено', 'uz-Latn': 'Zal stol koʻchirildi' },
  'dinein.table.status-changed': { en: 'Dinein table status changed', ru: 'Зал стол статус изменено', 'uz-Latn': 'Zal stol holat oʻzgartirildi' },
  'fiscal-terminal.health-checked': { en: 'Fiscal terminal health checked', ru: 'Фискальный терминал состояние проверено', 'uz-Latn': 'Fiskal terminal holat tekshirildi' },
  'fiscal-terminal.registered': { en: 'Fiscal terminal registered', ru: 'Фискальный терминал зарегистрировано', 'uz-Latn': 'Fiskal terminal roʻyxatdan oʻtkazildi' },
  'fiscal.document.retry': { en: 'Fiscal document retry', ru: 'Фискальный документ повтор', 'uz-Latn': 'Fiskal hujjat qayta urinish' },
  'fiscal.document.unblock': { en: 'Fiscal document unblock', ru: 'Фискальный документ разблокировка', 'uz-Latn': 'Fiskal hujjat blokdan chiqarish' },
  'fulfillment.delivery.cost-subsidy': { en: 'Fulfillment delivery cost subsidy', ru: 'Исполнение доставка стоимость субсидия', 'uz-Latn': 'Bajarish yetkazib berish narx subsidiya' },
  'fulfillment.dispatch.assign': { en: 'Fulfillment dispatch assign', ru: 'Исполнение диспетчеризация назначить', 'uz-Latn': 'Bajarish dispetcherlik tayinlash' },
  'fulfillment.dispatch.unassign': { en: 'Fulfillment dispatch unassign', ru: 'Исполнение диспетчеризация снять назначение', 'uz-Latn': 'Bajarish dispetcherlik tayinlashni bekor qilish' },
  'fulfillment.shipment.cascade-cancel': { en: 'Fulfillment shipment cascade cancel', ru: 'Исполнение отправление каскад отмена', 'uz-Latn': 'Bajarish joʻnatma kaskad bekor qilish' },
  'iam.identity_drift_detected': { en: 'IAM identity drift detected', ru: 'Доступ личность расхождение обнаружено', 'uz-Latn': 'Huquq shaxs farq aniqlandi' },
  'integration.secret_written': { en: 'Integration secret written', ru: 'Интеграция секрет записано', 'uz-Latn': 'Integratsiya sir yozildi' },
  'integration.sendpulse_import_run': { en: 'Integration sendpulse import run', ru: 'Интеграция SendPulse импорт запуск', 'uz-Latn': 'Integratsiya SendPulse import ishga tushirish' },
  'integration.telegram_auth_sign_in_redeemed': { en: 'Integration telegram auth sign in redeemed', ru: 'Интеграция Telegram вход вход в использовано', 'uz-Latn': 'Integratsiya Telegram kirish kirish da ishlatildi' },
  'integration.telegram_binding_created': { en: 'Integration telegram binding created', ru: 'Интеграция Telegram привязка создано', 'uz-Latn': 'Integratsiya Telegram bogʻlanish yaratildi' },
  'integration.telegram_binding_retired': { en: 'Integration telegram binding retired', ru: 'Интеграция Telegram привязка выведено из эксплуатации', 'uz-Latn': 'Integratsiya Telegram bogʻlanish chiqarib tashlandi' },
  'integration.telegram_customer_binding_created': { en: 'Integration telegram customer binding created', ru: 'Интеграция Telegram клиент привязка создано', 'uz-Latn': 'Integratsiya Telegram mijoz bogʻlanish yaratildi' },
  'integration.telegram_customer_binding_imported': { en: 'Integration telegram customer binding imported', ru: 'Интеграция Telegram клиент привязка импортировано', 'uz-Latn': 'Integratsiya Telegram mijoz bogʻlanish import qilindi' },
  'integration.telegram_link_code_issued': { en: 'Integration telegram link code issued', ru: 'Интеграция Telegram ссылка код выдано', 'uz-Latn': 'Integratsiya Telegram havola kod berildi' },
  'integration.telegram_staff_link_code_issued': { en: 'Integration telegram staff link code issued', ru: 'Интеграция Telegram сотрудник ссылка код выдано', 'uz-Latn': 'Integratsiya Telegram xodim havola kod berildi' },
  'integration.telegram_staff_link_created': { en: 'Integration telegram staff link created', ru: 'Интеграция Telegram сотрудник ссылка создано', 'uz-Latn': 'Integratsiya Telegram xodim havola yaratildi' },
  'integration.telegram_staff_link_revoked': { en: 'Integration telegram staff link revoked', ru: 'Интеграция Telegram сотрудник ссылка отозвано', 'uz-Latn': 'Integratsiya Telegram xodim havola bekor qilindi' },
  'integration.webhook_registered': { en: 'Integration webhook registered', ru: 'Интеграция вебхук зарегистрировано', 'uz-Latn': 'Integratsiya webhook roʻyxatdan oʻtkazildi' },
  'inventory.availability.set': { en: 'Inventory availability set', ru: 'Склад доступность установлено', 'uz-Latn': 'Ombor mavjudlik oʻrnatildi' },
  'kitchen.device.enrolled': { en: 'Kitchen device enrolled', ru: 'Кухня устройство зарегистрировано', 'uz-Latn': 'Oshxona qurilma roʻyxatga olindi' },
  'kitchen.device.revoked': { en: 'Kitchen device revoked', ru: 'Кухня устройство отозвано', 'uz-Latn': 'Oshxona qurilma bekor qilindi' },
  'legal-entity.assigned': { en: 'Legal entity assigned', ru: 'Юридический юрлицо назначено', 'uz-Latn': 'Yuridik yuridik shaxs tayinlandi' },
  'legal-entity.registered': { en: 'Legal entity registered', ru: 'Юридический юрлицо зарегистрировано', 'uz-Latn': 'Yuridik yuridik shaxs roʻyxatdan oʻtkazildi' },
  'legal-entity.updated': { en: 'Legal entity updated', ru: 'Юридический юрлицо обновлено', 'uz-Latn': 'Yuridik yuridik shaxs yangilandi' },
  'legal.terms.published': { en: 'Legal terms published', ru: 'Юридический условия опубликовано', 'uz-Latn': 'Yuridik shartlar eʻlon qilindi' },
  'location.service_state.changed': { en: 'Location service state changed', ru: 'Локация обслуживание состояние изменено', 'uz-Latn': 'Filial xizmat holat oʻzgartirildi' },
  'marketplace.handover.bypassed': { en: 'Marketplace handover bypassed', ru: 'Маркетплейс передача пропущено', 'uz-Latn': 'Marketpleys topshirish chetlab oʻtildi' },
  'media.asset.ingested': { en: 'Media asset ingested', ru: 'Медиа файл загружено', 'uz-Latn': 'Media fayl yuklandi' },
  'notifications.template.provider_review_recorded': { en: 'Notifications template provider review recorded', ru: 'Уведомления шаблон провайдер проверка зафиксировано', 'uz-Latn': 'Bildirishnomalar shablon provayder koʻrib chiqish qayd etildi' },
  'ordering.order.call_provenance_recorded': { en: 'Ordering order call provenance recorded', ru: 'Заказы заказ звонок источник зафиксировано', 'uz-Latn': 'Buyurtmalar buyurtma qoʻngʻiroq manba qayd etildi' },
  'partner.invoice.disputed': { en: 'Partner invoice disputed', ru: 'Партнёр счёт оспорено', 'uz-Latn': 'Hamkor hisob-faktura eʻtiroz bildirildi' },
  'partner.invoice.imported': { en: 'Partner invoice imported', ru: 'Партнёр счёт импортировано', 'uz-Latn': 'Hamkor hisob-faktura import qilindi' },
  'partner.invoice.line.acknowledged-unbilled': { en: 'Partner invoice line acknowledged unbilled', ru: 'Партнёр счёт строка подтверждено невыставленный', 'uz-Latn': 'Hamkor hisob-faktura qator tasdiqlandi hisob qilinmagan' },
  'partner.invoice.line.reconciled': { en: 'Partner invoice line reconciled', ru: 'Партнёр счёт строка сверено', 'uz-Latn': 'Hamkor hisob-faktura qator solishtirildi' },
  'partner.invoice.matched': { en: 'Partner invoice matched', ru: 'Партнёр счёт сопоставлено', 'uz-Latn': 'Hamkor hisob-faktura moslashtirildi' },
  'partner.invoice.variance.resolved': { en: 'Partner invoice variance resolved', ru: 'Партнёр счёт расхождение решено', 'uz-Latn': 'Hamkor hisob-faktura farq hal qilindi' },
  'payment-method.localized': { en: 'Payment method localized', ru: 'Платёж способ локализовано', 'uz-Latn': 'Toʻlov usul lokalizatsiya qilindi' },
  'payment-method.registered': { en: 'Payment method registered', ru: 'Платёж способ зарегистрировано', 'uz-Latn': 'Toʻlov usul roʻyxatdan oʻtkazildi' },
  'payment-method.updated': { en: 'Payment method updated', ru: 'Платёж способ обновлено', 'uz-Latn': 'Toʻlov usul yangilandi' },
  'payment.merchant_binding_secret_rotated': { en: 'Payment merchant binding secret rotated', ru: 'Платёж продавец привязка секрет обновлено', 'uz-Latn': 'Toʻlov sotuvchi bogʻlanish sir yangilandi' },
  'payments.remedy.verify': { en: 'Payments remedy verify', ru: 'Платежи компенсация проверить', 'uz-Latn': 'Toʻlovlar kompensatsiya tekshirish' },
  'pos.catalog_sync_applied': { en: 'POS catalog sync applied', ru: 'Касса каталог синхронизация применено', 'uz-Latn': 'Kassa katalog sinxronlash qoʻllanildi' },
  'pos.catalog_sync_resumed': { en: 'POS catalog sync resumed', ru: 'Касса каталог синхронизация возобновлено', 'uz-Latn': 'Kassa katalog sinxronlash davom ettirildi' },
  'pos.catalog_sync_review_decided': { en: 'POS catalog sync review decided', ru: 'Касса каталог синхронизация проверка решено', 'uz-Latn': 'Kassa katalog sinxronlash koʻrib chiqish qaror qilindi' },
  'pos.catalog_sync_started': { en: 'POS catalog sync started', ru: 'Касса каталог синхронизация начато', 'uz-Latn': 'Kassa katalog sinxronlash boshlandi' },
  'pos.export_push_requested': { en: 'POS export push requested', ru: 'Касса экспорт отправка запрошено', 'uz-Latn': 'Kassa eksport yuborish soʻralindi' },
  'pos.export_resolved': { en: 'POS export resolved', ru: 'Касса экспорт решено', 'uz-Latn': 'Kassa eksport hal qilindi' },
  'pos.mapping_bulk_auto_matched': { en: 'POS mapping bulk auto matched', ru: 'Касса сопоставление массовое авто сопоставлено', 'uz-Latn': 'Kassa moslashtirish ommaviy avto moslashtirildi' },
  'pos.mapping_created': { en: 'POS mapping created', ru: 'Касса сопоставление создано', 'uz-Latn': 'Kassa moslashtirish yaratildi' },
  'pos.mapping_retired': { en: 'POS mapping retired', ru: 'Касса сопоставление выведено из эксплуатации', 'uz-Latn': 'Kassa moslashtirish chiqarib tashlandi' },
  'pricing.price_book.activated': { en: 'Pricing price book activated', ru: 'Ценообразование цена книга активировано', 'uz-Latn': 'Narxlash narx kitob faollashtirildi' },
  'reference.public_holiday.added': { en: 'Reference public holiday added', ru: 'Справочник публичный праздник добавлено', 'uz-Latn': 'Maʻlumotnoma ochiq bayram qoʻshildi' },
  'reference.public_holiday.removed': { en: 'Reference public holiday removed', ru: 'Справочник публичный праздник удалено', 'uz-Latn': 'Maʻlumotnoma ochiq bayram oʻchirildi' },
  'report.export.completed': { en: 'Report export completed', ru: 'Отчёт экспорт завершено', 'uz-Latn': 'Hisobot eksport yakunlandi' },
  'reporting.business-calendar.holiday-added': { en: 'Reporting business calendar holiday added', ru: 'Отчётность бизнес календарь праздник добавлено', 'uz-Latn': 'Hisobotlar biznes taqvim bayram qoʻshildi' },
  'reporting.business-calendar.holiday-removed': { en: 'Reporting business calendar holiday removed', ru: 'Отчётность бизнес календарь праздник удалено', 'uz-Latn': 'Hisobotlar biznes taqvim bayram oʻchirildi' },
  'reporting.business-calendar.weekend-set': { en: 'Reporting business calendar weekend set', ru: 'Отчётность бизнес календарь выходные установлено', 'uz-Latn': 'Hisobotlar biznes taqvim dam olish kunlari oʻrnatildi' },
  'reporting.business-day-boundary.changed': { en: 'Reporting business day boundary changed', ru: 'Отчётность бизнес день граница изменено', 'uz-Latn': 'Hisobotlar biznes kun chegara oʻzgartirildi' },
  'reporting.metric.signed': { en: 'Reporting metric signed', ru: 'Отчётность метрика подписано', 'uz-Latn': 'Hisobotlar koʻrsatkich imzolandi' },
  'telemetry.courier_track.revealed': { en: 'Telemetry courier track revealed', ru: 'Телеметрия курьер трек раскрыто', 'uz-Latn': 'Telemetriya kuryer trek ochib berildi' },
  'telemetry.duty_session.closed': { en: 'Telemetry duty session closed', ru: 'Телеметрия смена сессия закрыто', 'uz-Latn': 'Telemetriya smena sessiya yopildi' },
  'telemetry.duty_session.opened': { en: 'Telemetry duty session opened', ru: 'Телеметрия смена сессия открыто', 'uz-Latn': 'Telemetriya smena sessiya ochildi' },
  'tenant.branch-tag.archived': { en: 'Tenant branch tag archived', ru: 'Компания филиал метка архивировано', 'uz-Latn': 'Kompaniya filial teg arxivlandi' },
  'tenant.branch-tag.assignment-set': { en: 'Tenant branch tag assignment set', ru: 'Компания филиал метка назначение установлено', 'uz-Latn': 'Kompaniya filial teg tayinlash oʻrnatildi' },
  'tenant.branch-tag.created': { en: 'Tenant branch tag created', ru: 'Компания филиал метка создано', 'uz-Latn': 'Kompaniya filial teg yaratildi' },
  'tenant.business_type.changed': { en: 'Tenant business type changed', ru: 'Компания бизнес тип изменено', 'uz-Latn': 'Kompaniya biznes turi oʻzgartirildi' },
  'tenant.configuration_value.set': { en: 'Tenant configuration value set', ru: 'Компания настройка значение установлено', 'uz-Latn': 'Kompaniya sozlama qiymat oʻrnatildi' },
  'tenant.country.changed': { en: 'Tenant country changed', ru: 'Компания страна изменено', 'uz-Latn': 'Kompaniya davlat oʻzgartirildi' },
  'tenant.onboarding_cancelled': { en: 'Tenant onboarding cancelled', ru: 'Компания регистрация отменено', 'uz-Latn': 'Kompaniya roʻyxatdan oʻtish bekor qilindi' },
  'tenant.onboarding_resumed': { en: 'Tenant onboarding resumed', ru: 'Компания регистрация возобновлено', 'uz-Latn': 'Kompaniya roʻyxatdan oʻtish davom ettirildi' },
  'tenant.onboarding_started': { en: 'Tenant onboarding started', ru: 'Компания регистрация начато', 'uz-Latn': 'Kompaniya roʻyxatdan oʻtish boshlandi' },
  'tenant.owner_invitation.accepted': { en: 'Tenant owner invitation accepted', ru: 'Компания владелец приглашение принято', 'uz-Latn': 'Kompaniya egasi taklifnoma qabul qilindi' },
  'tenant.owner_invitation.queued': { en: 'Tenant owner invitation queued', ru: 'Компания владелец приглашение в очереди', 'uz-Latn': 'Kompaniya egasi taklifnoma navbatga qoʻyildi' },
  'tenant.owner_invitation.recipient_revealed': { en: 'Tenant owner invitation recipient revealed', ru: 'Компания владелец приглашение получатель раскрыто', 'uz-Latn': 'Kompaniya egasi taklifnoma qabul qiluvchi ochib berildi' },
  'tenant.owner_invitation.resent': { en: 'Tenant owner invitation resent', ru: 'Компания владелец приглашение отправлено повторно', 'uz-Latn': 'Kompaniya egasi taklifnoma qayta yuborildi' },
  'tenant.owner_invitation.sent': { en: 'Tenant owner invitation sent', ru: 'Компания владелец приглашение отправлено', 'uz-Latn': 'Kompaniya egasi taklifnoma yuborildi' },
  'tenant.policy.authored': { en: 'Tenant policy authored', ru: 'Компания политика оформлено', 'uz-Latn': 'Kompaniya siyosat tuzildi' },
  'tenant.staff_invitation.accepted': { en: 'Tenant staff invitation accepted', ru: 'Компания сотрудник приглашение принято', 'uz-Latn': 'Kompaniya xodim taklifnoma qabul qilindi' },
  'tenant.staff_invitation.cancelled': { en: 'Tenant staff invitation cancelled', ru: 'Компания сотрудник приглашение отменено', 'uz-Latn': 'Kompaniya xodim taklifnoma bekor qilindi' },
  'tenant.staff_invitation.invited': { en: 'Tenant staff invitation invited', ru: 'Компания сотрудник приглашение приглашён', 'uz-Latn': 'Kompaniya xodim taklifnoma taklif qilindi' },
  'tenant.staff_invitation.orphan_left': { en: 'Tenant staff invitation orphan left', ru: 'Компания сотрудник приглашение без владельца вышел', 'uz-Latn': 'Kompaniya xodim taklifnoma egasiz chiqdi' },
  'tenant.staff_invitation.resent': { en: 'Tenant staff invitation resent', ru: 'Компания сотрудник приглашение отправлено повторно', 'uz-Latn': 'Kompaniya xodim taklifnoma qayta yuborildi' },
  'voice.presence.changed': { en: 'Voice presence changed', ru: 'Голос присутствие изменено', 'uz-Latn': 'Ovoz mavjudlik oʻzgartirildi' },
  'voice.screen_pop.caller_number_revealed': { en: 'Voice screen pop caller number revealed', ru: 'Голос экран всплытие звонящий номер раскрыто', 'uz-Latn': 'Ovoz ekran chiqib kelish qoʻngʻiroq qiluvchi raqam ochib berildi' },
};
