import { Pipe, PipeTransform, inject } from '@angular/core';

import { I18n, Locale, interpolate } from '../../../core/i18n/i18n';

/**
 * The Promotions screen's own strings (ADR 0140, row `6.1`) and the 7.9 promotion
 * report's (`report.*`), in all three locales.
 *
 * **A separate table, not more entries in `messages.*.ts`**, for the reason
 * `activity-log-action-sentences.ts` gives: the central catalogues sit in the
 * eager initial chunk (Russian, the default, always), and `angular.json`'s
 * initial-bundle budget exists to keep that chunk small. Roughly three hundred
 * strings for two lazy-loaded screens would have spent most of what the budget had
 * left. This module is reached only from the Promotions page, the promotion
 * report tab and their components, so it ships only to an operator who opens one
 * of them.
 *
 * What stays in the central catalogues is what a shared component renders from a
 * `MessageKey`: the eighteen condition names `q-condition-builder` shows
 * (`marketing.promotions.condition.*`) and the approvals worklist's action label.
 *
 * Parity is held the same way the catalogues hold it: every locale is typed as the
 * full English key set, so a string missing in `ru` or `uz-Latn` is a compile
 * error, and `promotion-texts.spec.ts` checks placeholders and the uz-Latn
 * apostrophe the way `i18n.spec.ts` does for the catalogues.
 */
const en = {
  'problem.name': 'Give the promotion a name.',
  'problem.code': 'The handle is 2 to 64 letters, digits, dashes or underscores.',
  'problem.group': 'Name the stacking group.',
  'problem.action': 'Add at least one action.',
  'problem.gift': 'Choose which dish is the gift.',
  'problem.condition': 'Finish or remove the condition with no value.',
  title: 'Promotions',
  intro:
    'Automatic discounts and markups that apply on their own when their conditions hold. A promotion is a draft until the rule checker passes it, and a second person may have to approve it before it reaches guests. Promo codes are on their own tab.',
  create: 'New promotion',
  newTitle: 'New promotion',
  loading: 'Loading',
  denied: 'No access to this brand’s promotions',
  empty: 'No promotion authored yet.',
  list: 'Promotions by stacking group',
  group: 'Group: {name}',
  'list.hint':
    'Within one group the offer worth most to the guest wins and priority only breaks ties. Drag to reorder; the switch turns a validated promotion on or a live one off.',
  archived: 'Archived ({count})',
  nothingOpen: 'Open a promotion from the list, or create a new one.',
  'row.description': '{code} · {status} · {scope}',
  dirty: 'You have unsaved changes. Save them before validating or activating.',
  'kind.DISCOUNT': 'Discount',
  'kind.MARKUP': 'Markup (raises the price)',
  'scope.ITEM': 'Matching products',
  'scope.ORDER': 'The whole order',
  'scope.DELIVERY': 'The delivery fee',
  'status.DRAFT': 'Draft',
  'status.VALIDATED': 'Validated',
  'status.ACTIVE': 'Active',
  'status.SUSPENDED': 'Suspended',
  'status.ARCHIVED': 'Archived',
  'channelType.WEB': 'Website',
  'channelType.IOS': 'iOS app',
  'channelType.ANDROID': 'Android app',
  'channelType.TELEGRAM': 'Telegram',
  'channelType.KIOSK': 'Kiosk',
  'channelType.QR_TABLE': 'QR at the table',
  'channelType.CALL_CENTRE': 'Call centre',
  'channelType.POS': 'Point of sale',
  'fulfillment.DELIVERY': 'Delivery',
  'fulfillment.PICKUP': 'Pickup',
  'fulfillment.DINE_IN': 'Dine-in',
  'action.ITEM_PERCENTAGE_DISCOUNT': 'Percentage off matching products',
  'action.ITEM_FIXED_DISCOUNT': 'Fixed amount off each matching unit',
  'action.ITEM_FIXED_PRICE': 'Fixed unit price (never raises a price)',
  'action.FREE_ITEM': 'Free gift dish',
  'action.ORDER_PERCENTAGE_DISCOUNT': 'Percentage off the order',
  'action.ORDER_FIXED_DISCOUNT': 'Fixed amount off the order',
  'action.FREE_DELIVERY': 'Free delivery',
  'action.REDUCED_DELIVERY': 'Reduced delivery fee',
  'action.ITEM_PERCENTAGE_MARKUP': 'Percentage markup on matching products',
  'action.ITEM_FIXED_MARKUP': 'Fixed markup on each matching unit',
  'adjustment.BASE_PRICE': 'Price',
  'adjustment.MODIFIER': 'Modifier',
  'adjustment.ITEM_DISCOUNT': 'Product discount',
  'adjustment.ORDER_DISCOUNT': 'Order discount',
  'adjustment.FEE': 'Delivery fee',
  'adjustment.TAX': 'Tax',
  'adjustment.ROUNDING': 'Rounding',
  'adjustment.DELIVERY_FEE_WAIVER': 'Free-delivery threshold',
  'adjustment.DELIVERY_FEE_BENEFIT': 'Delivery benefit',
  'adjustment.DELIVERY_TARIFF_DISCOUNT': 'Tariff delivery discount',
  'adjustment.ITEM_MARKUP': 'Product markup',
  'verdict.COUPON_NOT_PRESENTED': 'Needs a promo code that was not presented',
  'verdict.LIMIT_REACHED': 'Its redemption limit is used up',
  'verdict.NOT_CLAIMED_AT_PLACEMENT':
    'The order did not claim it when it was placed, and an amendment cannot',
  'verdict.OUTSIDE_WINDOW': 'Outside its validity window',
  'verdict.ZERO_BENEFIT': 'Would give nothing on this cart',
  'verdict.CURRENCY_MISMATCH': 'In another currency than the price book',
  'verdict.APPLIED': 'Applied: {amount}',
  'verdict.CONDITION_FAILED': 'Condition {n} did not hold',
  'verdict.CONDITION_FAILED.any': 'A condition did not hold',
  'verdict.LOST_TO': 'Lost to {others}',
  'verdict.SUPPRESSED_BY_EXCLUSIVE': 'Set aside by the exclusive {others}',
  'action.validate': 'Run the rule checker',
  'action.activate': 'Activate',
  'action.suspend': 'Suspend',
  'action.resume': 'Resume',
  'action.archive': 'Archive',
  'action.close': 'Close',
  'dialog.cancel': 'Cancel',
  'activate.title': 'Put this promotion in front of guests?',
  'activate.body':
    'A markup, or a discount above the configured thresholds, needs a second person to approve it first; you will be told if so. Anything below the thresholds goes live at once.',
  'activate.reason': 'Note for the approver (optional)',
  'activate.confirm': 'Activate',
  'archive.title': 'Archive this promotion?',
  'archive.body':
    'It stops applying to new orders and cannot be edited or brought back. Orders that already hold it keep it, and its history stays.',
  'discard.title': 'Discard unsaved changes?',
  'discard.body': 'What you changed in this promotion has not been saved.',
  'discard.confirm': 'Discard',
  'discard.keep': 'Keep editing',
  'notice.saved': 'Saved as a draft. Run the rule checker next.',
  'notice.validated': 'The rule checker passed it. It can be activated.',
  'notice.refused': 'The rule checker refused it. It stays a draft.',
  'notice.activated': 'The promotion is live.',
  'notice.pending': 'Waiting for a second person to approve the activation.',
  'notice.suspended': 'The promotion no longer applies to new orders.',
  'notice.resumed': 'The promotion is live again.',
  'notice.archived': 'The promotion is archived.',
  'notice.reordered': 'Priority order saved.',
  pending:
    'Request {id} is waiting for a second person. They decide it under People, Approvals; press Activate again once they have.',
  'pending.link': 'Open approvals',
  'locked.active':
    'A live promotion is never edited in place. Suspend it, edit it, run the rule checker and activate it again.',
  'locked.archived': 'An archived promotion is history and cannot be edited.',
  'error.toggleNeedsValidation':
    'Only a validated promotion can be switched on. Open it and run the rule checker first.',
  'error.toggleNotLive': 'Only a live promotion can be switched off.',
  'error.unsaved': 'Save or discard the changes in the open promotion first.',
  'validation.ok': 'The rule checker passed it.',
  'validation.refused': 'The rule checker refused it:',
  'issue.place': 'item {n}',
  'issue.NAME_REQUIRED': 'A promotion needs a name.',
  'issue.CODE_INVALID': 'The handle must be 2 to 64 letters, digits, dashes or underscores.',
  'issue.STACKING_GROUP_REQUIRED': 'A stacking group of at most 64 characters is required.',
  'issue.CURRENCY_INVALID': 'The currency must be a 3-letter ISO code.',
  'issue.MAXIMUM_INVALID': 'A maximum discount must be positive, or switched off.',
  'issue.EXCLUSIVE_WITH_MARKUP': 'A markup cannot be exclusive.',
  'issue.MARKUP_SCOPE_INVALID': 'A markup lands on products, never on delivery.',
  'issue.ORDER_MARKUP_NOT_AVAILABLE':
    'An order-level markup (a service charge) is not available yet; only product markups can be authored.',
  'issue.MARKUP_NOT_COUPON_GATED': 'A markup cannot require a promo code.',
  'issue.NO_ACTION': 'Add at least one action.',
  'issue.ACTION_SCOPE_MISMATCH': 'This action does not belong to the promotion’s type and scope.',
  'issue.OPERAND_INVALID': 'A value is missing or out of range.',
  'issue.PERCENTAGE_OVER_100': 'A percentage cannot exceed 100%.',
  'issue.FREE_ITEM_UNBOUNDED':
    'A gift needs a quantity of at least 1: an unbounded gift gives away the whole cart.',
  'issue.UNKNOWN_REFERENCE': 'It names something that does not belong to this brand.',
  'issue.NO_PRICED_VARIANT_MATCH':
    'None of the named dishes has an active price, so this promotion can never apply.',
  'issue.WEEKDAYS_EMPTY': 'Select at least one weekday.',
  'issue.WINDOW_INVERTED':
    'A time window must end after it starts, and may not start and end at the same minute.',
  'issue.SEQUENCE_NEEDS_CUSTOMER_LIMIT':
    'A first-order or Nth-order promotion must limit each customer to one redemption; that claim is what stops two quick checkouts both being first.',
  'issue.LIMIT_ON_COUPON_PROMOTION':
    'A promo-code promotion carries its limits on the code, not here.',
  'issue.STACKING_GROUP_MIXES_SCOPES':
    'A product promotion cannot share a stacking group with an order or delivery promotion; use a different group.',
  'issue.CURRENCY_MISMATCH': 'The promotion’s currency differs from the brand’s price book.',
  'issue.UNCAPPED_PERCENTAGE':
    'A percentage discount with no maximum takes a share of any basket, however large.',
  'pane.rule': 'Rule',
  'pane.simulate': 'Simulator',
  'pane.history': 'Versions',
  'pane.redemptions': 'Redemptions',
  'history.intro':
    'Every validation, activation and priority change records the rule exactly as the engine read it, newest first. An old receipt is explained against the version that priced it.',
  'history.empty': 'No version recorded yet: a promotion is recorded when it is validated.',
  'history.version': 'Version',
  'history.reason': 'Why',
  'history.by': 'By',
  'history.when': 'When',
  'history.activated': 'Activated by {by} on {when}.',
  'redemptions.loading': 'Loading redemptions',
  'redemptions.empty': 'This promotion has not been redeemed yet.',
  'redemptions.error': 'The redemptions could not be loaded.',
  'redemptions.intro':
    'One row per order, newest first, at most 200. An amended order moves its row instead of adding one. Ids only: no name or contact is shown here.',
  'redemptions.order': 'Order',
  'redemptions.version': 'Version',
  'redemptions.discount': 'Discount',
  'redemptions.markup': 'Markup',
  'redemptions.status': 'Status',
  'editor.basics': 'Basics',
  'editor.name': 'Name (internal, for this list and the reports)',
  'editor.code': 'Handle',
  'editor.code.hint':
    'Unique in this brand: 2 to 64 letters, digits, dashes or underscores. Guests never see it.',
  'editor.kind': 'Type',
  'editor.scope': 'Applies to',
  'editor.currency': 'Currency',
  'editor.markupNote':
    'A markup raises the price of matching products before any discount, and always needs a second person to activate it. A service charge on the whole order is not available yet.',
  'editor.group': 'Stacking group',
  'editor.group.hint':
    'Within one group the offer worth most to the guest wins; different groups add up. A product promotion cannot share a group with an order or delivery one.',
  'editor.exclusive': 'Exclusive',
  'editor.exclusive.hint':
    'An exclusive promotion is counted as if it were the only discount; the guest then receives the larger of it and the best combination of the others. A promo code is always exclusive.',
  'editor.window': 'Validity',
  'editor.validFrom': 'Valid from',
  'editor.validUntil': 'Valid until',
  'editor.window.hint':
    'Leave empty for “from activation” and “never lapses”. Times are in this device’s time zone; a time-of-day condition uses the branch’s own.',
  'editor.conditions': 'Conditions',
  'editor.conditions.hint':
    'Every condition must hold; leave none to apply to every order. There is no “or”: for either-or, author two promotions in the same group.',
  'editor.menuBranch': 'Dish lists come from the menu of',
  'editor.menuLoading': 'Loading the menu',
  'editor.actions': 'What it does',
  'editor.actionType': 'Action',
  'editor.addAction': 'Add an action',
  'editor.removeAction': 'Remove this action',
  'editor.percent': 'Percentage',
  'editor.amount': 'Amount',
  'editor.unitPrice': 'New unit price',
  'editor.reduceBy': 'Reduce the fee by',
  'editor.reduceBy.PERCENT': 'A percentage',
  'editor.reduceBy.AMOUNT': 'A fixed amount',
  'editor.gift': 'Gift dishes',
  'editor.giftQuantity': 'Units free, at most',
  'editor.giftMode': 'How often',
  'editor.giftMode.ONCE': 'Once per order',
  'editor.giftMode.PER_MULTIPLE': 'For every n matched units',
  'editor.giftTrigger': 'Matched units per gift unit',
  'editor.gift.hint':
    'The gift is bounded across the whole cart however many lines the dish sits on, and pricing never adds a line the cart does not hold.',
  'editor.limits': 'Caps and limits',
  'editor.hasCap': 'Cap the maximum discount',
  'editor.cap': 'Maximum discount',
  'editor.hasTotalLimit': 'Limit the total number of redemptions',
  'editor.totalLimit': 'Redemptions allowed in total',
  'editor.hasCustomerLimit': 'Limit redemptions per customer',
  'editor.customerLimit': 'Redemptions per customer',
  'editor.limits.hint':
    'A slot is not returned when its order is cancelled. A guest’s cart has no customer to count against, so the per-customer limit does not apply to guests.',
  'editor.loyalty': 'Loyalty points',
  'editor.loyaltyAccrual': 'Points earned on an order with this promotion',
  'editor.loyaltyRedemption': 'Spending points on such an order',
  'loyalty.accrual.ACCRUE': 'Earn points as usual',
  'loyalty.accrual.SUPPRESS': 'Earn no points',
  'loyalty.redemption.ALLOW': 'Allowed',
  'loyalty.redemption.BLOCK': 'Not allowed',
  'editor.unsupported':
    'This promotion uses rules this console cannot draw ({types}). It is shown read-only so nothing is lost; change it through the API, or archive it and draft a new one.',
  'editor.save': 'Save as draft',
  'editor.saving': 'Saving…',
  'editor.cancel': 'Cancel',
  'sim.title': 'Simulator',
  'sim.intro':
    'Prices a made-up cart with the real engine and shows, for every promotion in the brand, whether it applied or why it did not. Nothing is saved: no quote, no redemption, no counter.',
  'sim.branch': 'Branch',
  'sim.channel': 'Sales channel',
  'sim.mode': 'Order type',
  'sim.payment': 'Payment method',
  'sim.instant': 'Service time (empty is now)',
  'sim.coupon': 'Promo code (optional)',
  'sim.latitude': 'Delivery latitude',
  'sim.longitude': 'Delivery longitude',
  'sim.destination.hint':
    'Without a point the delivery fee and zone are not resolved, so a delivery-zone condition cannot hold.',
  'sim.customer': 'The customer, as facts',
  'sim.customer.hint':
    'Never an account: only where this order would sit in their history and which audiences they are in.',
  'sim.brandPosition': 'This would be their order number at the brand',
  'sim.channelPosition': '…and their order number through this channel',
  'sim.cart': 'Cart',
  'sim.addDish': 'Add a dish: start typing its name',
  'sim.cart.empty': 'Add at least one dish.',
  'sim.quantity': 'Quantity',
  'sim.removeLine': 'Remove this line',
  'sim.try': 'Try something else',
  'sim.useCandidate': 'Include the promotion I am editing, as it stands (unsaved)',
  'sim.replay': 'Rule version of {code}',
  'sim.replay.current': 'The current one',
  'sim.replay.version': 'Version {version}',
  'sim.run': 'Price this cart',
  'sim.running': 'Pricing…',
  'sim.subtotal': 'Subtotal',
  'sim.discount': 'Discount',
  'sim.fee': 'Delivery fee',
  'sim.tax': 'Tax',
  'sim.total': 'Total',
  'sim.inputs': 'Priced at {instant} ({zone}) as {mode}.',
  'sim.noAccrual': 'An applied promotion suppresses loyalty points on this order.',
  'sim.noRedemption': 'An applied promotion blocks spending loyalty points on this order.',
  'sim.adjustments': 'How the total was built',
  'sim.trace': 'Every promotion of the brand, and what happened to it',
  'report.intro':
    'What each automatic promotion and promo code gave away and earned, from the redemption facts built at day close. The newest business day or two may still be settling.',
  'report.loading': 'Loading…',
  'report.empty': 'No promotion was redeemed in this range.',
  'report.column.promotion': 'Promotion',
  'report.column.source': 'Source',
  'report.column.redemptions': 'Redemptions',
  'report.column.customers': 'Unique customers',
  'report.column.discount': 'Discount given',
  'report.column.markup': 'Markup',
  'report.column.revenue': 'Revenue with it',
  'report.column.checkWith': 'Average check with it',
  'report.column.checkWithout': 'Average check without it',
  'report.source.AUTOMATIC': 'Automatic',
  'report.source.COUPON': 'Promo code',
  'report.source.GRANT': 'Benefit grant',
  'report.status.none': 'Not closed yet',
  'report.comparison':
    'The two average checks are a comparison over the same brand and period, not an uplift: customers who use a promotion differ from those who do not. Cancelled, rejected, expired and payment-failed orders are left out here and stay in the log below.',
  'report.log.title': 'Redemption log',
  'report.log.forPromotion': 'Redemption log for {code}',
  'report.log.all': 'Show every promotion',
  'report.log.empty': 'No redemption to list for this selection.',
  'report.log.intro':
    'Newest first, at most 200 rows. A cancelled order is listed with its status. The customer is shown as a pseudonym.',
  'report.log.date': 'Redeemed',
  'report.log.order': 'Order',
  'report.log.customer': 'Customer (pseudonym)',
  'report.log.status': 'Order status',
  'report.log.channel': 'Channel',
  'report.log.who': 'Who redeemed it',
  'report.log.showCustomer': 'Show customer',
  'report.log.openCustomer': 'Open customer card',
  'report.log.guestOrder': 'Guest order: there is no customer account',
  'report.log.revealDenied': 'You may not view this customer.',
  'report.log.revealFailed': 'The customer could not be looked up.',
  'report.log.revealRetry': 'Try again',
  'report.log.revealNote':
    'Showing a customer is recorded in the audit log against that customer, with who looked.',
};

export type PromotionTextKey = keyof typeof en;

const ru: Record<PromotionTextKey, string> = {
  'problem.name': 'Укажите название акции.',
  'problem.code': 'Код: от 2 до 64 букв, цифр, дефисов или подчёркиваний.',
  'problem.group': 'Укажите группу совмещения.',
  'problem.action': 'Добавьте хотя бы одно действие.',
  'problem.gift': 'Выберите, какое блюдо идёт в подарок.',
  'problem.condition': 'Заполните или удалите условие без значения.',
  title: 'Промоакции',
  intro:
    'Автоматические скидки и наценки, которые применяются сами, когда выполнены условия. Акция остаётся черновиком, пока её не пропустит проверка правил, а запуск может потребовать подтверждения второго человека. Промокоды — на отдельной вкладке.',
  create: 'Новая акция',
  newTitle: 'Новая акция',
  loading: 'Загрузка',
  denied: 'Нет доступа к акциям этого бренда',
  empty: 'Акций пока нет.',
  list: 'Акции по группам совмещения',
  group: 'Группа: {name}',
  'list.hint':
    'Внутри группы побеждает предложение, более выгодное гостю, а приоритет только разрешает ничью. Перетащите, чтобы изменить порядок; переключатель включает проверенную акцию или выключает действующую.',
  archived: 'В архиве ({count})',
  nothingOpen: 'Откройте акцию из списка или создайте новую.',
  'row.description': '{code} · {status} · {scope}',
  dirty: 'Есть несохранённые изменения. Сохраните их перед проверкой или запуском.',
  'kind.DISCOUNT': 'Скидка',
  'kind.MARKUP': 'Наценка (повышает цену)',
  'scope.ITEM': 'Подходящие позиции',
  'scope.ORDER': 'Весь заказ',
  'scope.DELIVERY': 'Стоимость доставки',
  'status.DRAFT': 'Черновик',
  'status.VALIDATED': 'Проверена',
  'status.ACTIVE': 'Активна',
  'status.SUSPENDED': 'Приостановлена',
  'status.ARCHIVED': 'В архиве',
  'channelType.WEB': 'Сайт',
  'channelType.IOS': 'Приложение iOS',
  'channelType.ANDROID': 'Приложение Android',
  'channelType.TELEGRAM': 'Telegram',
  'channelType.KIOSK': 'Киоск',
  'channelType.QR_TABLE': 'QR на столе',
  'channelType.CALL_CENTRE': 'Колл-центр',
  'channelType.POS': 'Касса',
  'fulfillment.DELIVERY': 'Доставка',
  'fulfillment.PICKUP': 'Самовывоз',
  'fulfillment.DINE_IN': 'В зале',
  'action.ITEM_PERCENTAGE_DISCOUNT': 'Процент скидки на подходящие позиции',
  'action.ITEM_FIXED_DISCOUNT': 'Фиксированная скидка на каждую подходящую единицу',
  'action.ITEM_FIXED_PRICE': 'Фиксированная цена за единицу (цену не повышает)',
  'action.FREE_ITEM': 'Блюдо в подарок',
  'action.ORDER_PERCENTAGE_DISCOUNT': 'Процент скидки на заказ',
  'action.ORDER_FIXED_DISCOUNT': 'Фиксированная скидка на заказ',
  'action.FREE_DELIVERY': 'Бесплатная доставка',
  'action.REDUCED_DELIVERY': 'Сниженная стоимость доставки',
  'action.ITEM_PERCENTAGE_MARKUP': 'Процентная наценка на подходящие позиции',
  'action.ITEM_FIXED_MARKUP': 'Фиксированная наценка на каждую подходящую единицу',
  'adjustment.BASE_PRICE': 'Цена',
  'adjustment.MODIFIER': 'Модификатор',
  'adjustment.ITEM_DISCOUNT': 'Скидка на позицию',
  'adjustment.ORDER_DISCOUNT': 'Скидка на заказ',
  'adjustment.FEE': 'Доставка',
  'adjustment.TAX': 'Налог',
  'adjustment.ROUNDING': 'Округление',
  'adjustment.DELIVERY_FEE_WAIVER': 'Порог бесплатной доставки',
  'adjustment.DELIVERY_FEE_BENEFIT': 'Льгота на доставку',
  'adjustment.DELIVERY_TARIFF_DISCOUNT': 'Скидка тарифа доставки',
  'adjustment.ITEM_MARKUP': 'Наценка на позицию',
  'verdict.COUPON_NOT_PRESENTED': 'Нужен промокод, который не предъявлен',
  'verdict.LIMIT_REACHED': 'Лимит применений исчерпан',
  'verdict.NOT_CLAIMED_AT_PLACEMENT':
    'Заказ не занял её при оформлении, а изменение заказа не может',
  'verdict.OUTSIDE_WINDOW': 'Вне срока действия',
  'verdict.ZERO_BENEFIT': 'Не даст выгоды на этой корзине',
  'verdict.CURRENCY_MISMATCH': 'В другой валюте, чем прайс-лист',
  'verdict.APPLIED': 'Применена: {amount}',
  'verdict.CONDITION_FAILED': 'Условие {n} не выполнено',
  'verdict.CONDITION_FAILED.any': 'Условие не выполнено',
  'verdict.LOST_TO': 'Уступила: {others}',
  'verdict.SUPPRESSED_BY_EXCLUSIVE': 'Вытеснена эксклюзивной акцией {others}',
  'action.validate': 'Проверить правила',
  'action.activate': 'Запустить',
  'action.suspend': 'Приостановить',
  'action.resume': 'Возобновить',
  'action.archive': 'В архив',
  'action.close': 'Закрыть',
  'dialog.cancel': 'Отмена',
  'activate.title': 'Запустить акцию для гостей?',
  'activate.body':
    'Наценке или скидке выше установленных порогов нужно подтверждение второго человека — вы увидите, если оно потребуется. Всё, что ниже порогов, запускается сразу.',
  'activate.reason': 'Комментарий для подтверждающего (необязательно)',
  'activate.confirm': 'Запустить',
  'archive.title': 'Отправить акцию в архив?',
  'archive.body':
    'Она перестанет применяться к новым заказам, её нельзя будет изменить или вернуть. Заказы, к которым она уже применена, её сохранят, история останется.',
  'discard.title': 'Отбросить несохранённые изменения?',
  'discard.body': 'Изменения в этой акции не сохранены.',
  'discard.confirm': 'Отбросить',
  'discard.keep': 'Продолжить правку',
  'notice.saved': 'Сохранено как черновик. Теперь запустите проверку правил.',
  'notice.validated': 'Проверка правил пройдена. Акцию можно запускать.',
  'notice.refused': 'Проверка правил не пройдена. Акция остаётся черновиком.',
  'notice.activated': 'Акция запущена.',
  'notice.pending': 'Ожидаем подтверждения запуска вторым человеком.',
  'notice.suspended': 'Акция больше не применяется к новым заказам.',
  'notice.resumed': 'Акция снова действует.',
  'notice.archived': 'Акция отправлена в архив.',
  'notice.reordered': 'Порядок приоритета сохранён.',
  pending:
    'Запрос {id} ждёт второго человека. Решение принимается в разделе «Люди → Согласования»; нажмите «Запустить» ещё раз, когда оно будет принято.',
  'pending.link': 'Открыть согласования',
  'locked.active':
    'Действующую акцию не правят на месте. Приостановите её, измените, пройдите проверку правил и запустите снова.',
  'locked.archived': 'Акция в архиве — это история, её нельзя изменить.',
  'error.toggleNeedsValidation':
    'Включить можно только проверенную акцию. Откройте её и сначала пройдите проверку правил.',
  'error.toggleNotLive': 'Выключить можно только действующую акцию.',
  'error.unsaved': 'Сначала сохраните или отбросьте изменения в открытой акции.',
  'validation.ok': 'Проверка правил пройдена.',
  'validation.refused': 'Проверка правил не пройдена:',
  'issue.place': 'пункт {n}',
  'issue.NAME_REQUIRED': 'Нужно название акции.',
  'issue.CODE_INVALID': 'Код: от 2 до 64 букв, цифр, дефисов или подчёркиваний.',
  'issue.STACKING_GROUP_REQUIRED': 'Нужна группа совмещения не длиннее 64 символов.',
  'issue.CURRENCY_INVALID': 'Валюта — трёхбуквенный код ISO.',
  'issue.MAXIMUM_INVALID': 'Максимальная скидка должна быть положительной либо отключена.',
  'issue.EXCLUSIVE_WITH_MARKUP': 'Наценка не может быть эксклюзивной.',
  'issue.MARKUP_SCOPE_INVALID': 'Наценка действует на позиции, но не на доставку.',
  'issue.ORDER_MARKUP_NOT_AVAILABLE':
    'Наценка на весь заказ (сервисный сбор) пока недоступна; можно создавать только наценки на позиции.',
  'issue.MARKUP_NOT_COUPON_GATED': 'Наценка не может требовать промокод.',
  'issue.NO_ACTION': 'Добавьте хотя бы одно действие.',
  'issue.ACTION_SCOPE_MISMATCH': 'Это действие не подходит типу и области акции.',
  'issue.OPERAND_INVALID': 'Значение не заполнено или вне допустимого диапазона.',
  'issue.PERCENTAGE_OVER_100': 'Процент не может быть больше 100.',
  'issue.FREE_ITEM_UNBOUNDED':
    'Подарку нужно количество не меньше 1: безлимитный подарок отдаст всю корзину.',
  'issue.UNKNOWN_REFERENCE': 'Указано то, чего нет в этом бренде.',
  'issue.NO_PRICED_VARIANT_MATCH':
    'Ни у одного из указанных блюд нет действующей цены, акция никогда не сработает.',
  'issue.WEEKDAYS_EMPTY': 'Выберите хотя бы один день недели.',
  'issue.WINDOW_INVERTED':
    'Период должен заканчиваться позже начала и не может начинаться и заканчиваться в одну минуту.',
  'issue.SEQUENCE_NEEDS_CUSTOMER_LIMIT':
    'Акция на первый или N-й заказ должна ограничивать клиента одним применением: именно это не даёт двум быстрым заказам оба оказаться первыми.',
  'issue.LIMIT_ON_COUPON_PROMOTION': 'Лимиты акции с промокодом задаются на промокоде, а не здесь.',
  'issue.STACKING_GROUP_MIXES_SCOPES':
    'Акция на позиции не может делить группу совмещения с акцией на заказ или доставку; выберите другую группу.',
  'issue.CURRENCY_MISMATCH': 'Валюта акции не совпадает с валютой прайс-листа бренда.',
  'issue.UNCAPPED_PERCENTAGE':
    'Процентная скидка без максимума берёт долю любой корзины, какой бы большой она ни была.',
  'pane.rule': 'Правило',
  'pane.simulate': 'Симулятор',
  'pane.history': 'Версии',
  'pane.redemptions': 'Применения',
  'history.intro':
    'Каждая проверка, запуск и смена приоритета фиксирует правило ровно так, как его прочитал движок; новые версии сверху. Старый чек объясняется той версией, по которой он посчитан.',
  'history.empty': 'Версий пока нет: акция фиксируется при проверке правил.',
  'history.version': 'Версия',
  'history.reason': 'Повод',
  'history.by': 'Кто',
  'history.when': 'Когда',
  'history.activated': 'Запущена: {by}, {when}.',
  'redemptions.loading': 'Загрузка применений',
  'redemptions.empty': 'Эта акция ещё не применялась.',
  'redemptions.error': 'Не удалось загрузить применения.',
  'redemptions.intro':
    'Одна строка на заказ, новые сверху, не более 200. Изменённый заказ перемещает свою строку, а не добавляет новую. Только идентификаторы: имени и контактов здесь нет.',
  'redemptions.order': 'Заказ',
  'redemptions.version': 'Версия',
  'redemptions.discount': 'Скидка',
  'redemptions.markup': 'Наценка',
  'redemptions.status': 'Статус',
  'editor.basics': 'Основное',
  'editor.name': 'Название (внутреннее, для списка и отчётов)',
  'editor.code': 'Код акции',
  'editor.code.hint':
    'Уникален в бренде: от 2 до 64 букв, цифр, дефисов или подчёркиваний. Гости его не видят.',
  'editor.kind': 'Тип',
  'editor.scope': 'Действует на',
  'editor.currency': 'Валюта',
  'editor.markupNote':
    'Наценка повышает цену подходящих позиций до любых скидок и всегда требует подтверждения второго человека. Сервисный сбор на весь заказ пока недоступен.',
  'editor.group': 'Группа совмещения',
  'editor.group.hint':
    'Внутри группы побеждает предложение, более выгодное гостю; разные группы суммируются. Акция на позиции не может делить группу с акцией на заказ или доставку.',
  'editor.exclusive': 'Эксклюзивная',
  'editor.exclusive.hint':
    'Эксклюзивная акция считается так, будто других скидок нет; гость получает большее из неё и лучшего сочетания остальных. Промокод всегда эксклюзивен.',
  'editor.window': 'Срок действия',
  'editor.validFrom': 'Действует с',
  'editor.validUntil': 'Действует до',
  'editor.window.hint':
    'Пусто — «с момента запуска» и «без срока». Время — по часовому поясу этого устройства; условие «время суток» считается по времени филиала.',
  'editor.conditions': 'Условия',
  'editor.conditions.hint':
    'Должны выполняться все условия; без условий акция действует на любой заказ. Нет «или»: для «либо-либо» создайте две акции в одной группе.',
  'editor.menuBranch': 'Списки блюд — из меню филиала',
  'editor.menuLoading': 'Загрузка меню',
  'editor.actions': 'Что делает',
  'editor.actionType': 'Действие',
  'editor.addAction': 'Добавить действие',
  'editor.removeAction': 'Удалить это действие',
  'editor.percent': 'Процент',
  'editor.amount': 'Сумма',
  'editor.unitPrice': 'Новая цена за единицу',
  'editor.reduceBy': 'Снизить стоимость на',
  'editor.reduceBy.PERCENT': 'Процент',
  'editor.reduceBy.AMOUNT': 'Фиксированную сумму',
  'editor.gift': 'Блюда в подарок',
  'editor.giftQuantity': 'Бесплатных единиц, не более',
  'editor.giftMode': 'Как часто',
  'editor.giftMode.ONCE': 'Один раз на заказ',
  'editor.giftMode.PER_MULTIPLE': 'За каждые n подходящих единиц',
  'editor.giftTrigger': 'Подходящих единиц на одну подарочную',
  'editor.gift.hint':
    'Подарок ограничен на всю корзину, на скольких бы строках ни стояло блюдо; цена никогда не добавляет строку, которой нет в корзине.',
  'editor.limits': 'Потолок и лимиты',
  'editor.hasCap': 'Ограничить максимальную скидку',
  'editor.cap': 'Максимальная скидка',
  'editor.hasTotalLimit': 'Ограничить общее число применений',
  'editor.totalLimit': 'Всего применений',
  'editor.hasCustomerLimit': 'Ограничить применения на клиента',
  'editor.customerLimit': 'Применений на клиента',
  'editor.limits.hint':
    'Слот не возвращается, когда заказ отменён. У гостевой корзины нет клиента, по которому считать, поэтому лимит на клиента гостей не касается.',
  'editor.loyalty': 'Баллы лояльности',
  'editor.loyaltyAccrual': 'Баллы за заказ с этой акцией',
  'editor.loyaltyRedemption': 'Списание баллов на таком заказе',
  'loyalty.accrual.ACCRUE': 'Начислять как обычно',
  'loyalty.accrual.SUPPRESS': 'Не начислять',
  'loyalty.redemption.ALLOW': 'Разрешено',
  'loyalty.redemption.BLOCK': 'Запрещено',
  'editor.unsupported':
    'В этой акции есть правила, которые консоль не умеет показывать ({types}). Она открыта только для чтения, чтобы ничего не потерять; измените её через API или архивируйте и создайте новую.',
  'editor.save': 'Сохранить как черновик',
  'editor.saving': 'Сохранение…',
  'editor.cancel': 'Отмена',
  'sim.title': 'Симулятор',
  'sim.intro':
    'Считает придуманную корзину настоящим движком и показывает по каждой акции бренда, применилась ли она или почему нет. Ничего не сохраняется: ни расчёт, ни применение, ни счётчик.',
  'sim.branch': 'Филиал',
  'sim.channel': 'Канал продаж',
  'sim.mode': 'Тип заказа',
  'sim.payment': 'Способ оплаты',
  'sim.instant': 'Время обслуживания (пусто — сейчас)',
  'sim.coupon': 'Промокод (необязательно)',
  'sim.latitude': 'Широта доставки',
  'sim.longitude': 'Долгота доставки',
  'sim.destination.hint':
    'Без точки стоимость и зона доставки не определяются, поэтому условие по зоне доставки не выполнится.',
  'sim.customer': 'Клиент в виде фактов',
  'sim.customer.hint':
    'Не аккаунт: только то, каким по счёту был бы этот заказ и в каких аудиториях состоит клиент.',
  'sim.brandPosition': 'Это был бы их заказ номер (в бренде)',
  'sim.channelPosition': '…и номер заказа через этот канал',
  'sim.cart': 'Корзина',
  'sim.addDish': 'Добавьте блюдо: начните вводить название',
  'sim.cart.empty': 'Добавьте хотя бы одно блюдо.',
  'sim.quantity': 'Количество',
  'sim.removeLine': 'Удалить эту строку',
  'sim.try': 'Попробовать другое',
  'sim.useCandidate': 'Учесть редактируемую акцию в текущем виде (несохранённую)',
  'sim.replay': 'Версия правила {code}',
  'sim.replay.current': 'Текущая',
  'sim.replay.version': 'Версия {version}',
  'sim.run': 'Посчитать корзину',
  'sim.running': 'Считаем…',
  'sim.subtotal': 'Подытог',
  'sim.discount': 'Скидка',
  'sim.fee': 'Доставка',
  'sim.tax': 'Налог',
  'sim.total': 'Итого',
  'sim.inputs': 'Посчитано на {instant} ({zone}), тип заказа: {mode}.',
  'sim.noAccrual': 'Применённая акция отключает начисление баллов на этом заказе.',
  'sim.noRedemption': 'Применённая акция запрещает списание баллов на этом заказе.',
  'sim.adjustments': 'Из чего сложился итог',
  'sim.trace': 'Все акции бренда и что с ними произошло',
  'report.intro':
    'Сколько отдала и принесла каждая автоматическая акция и промокод — по фактам применений, которые строятся при закрытии дня. Последний-два рабочих дня могут ещё досчитываться.',
  'report.loading': 'Загрузка…',
  'report.empty': 'За этот период ни одна акция не применялась.',
  'report.column.promotion': 'Акция',
  'report.column.source': 'Источник',
  'report.column.redemptions': 'Применений',
  'report.column.customers': 'Уникальных клиентов',
  'report.column.discount': 'Дано скидок',
  'report.column.markup': 'Наценка',
  'report.column.revenue': 'Выручка с акцией',
  'report.column.checkWith': 'Средний чек с акцией',
  'report.column.checkWithout': 'Средний чек без акции',
  'report.source.AUTOMATIC': 'Автоматическая',
  'report.source.COUPON': 'Промокод',
  'report.source.GRANT': 'Персональная выгода',
  'report.status.none': 'Ещё не закрыт',
  'report.comparison':
    'Два средних чека — сравнение по тому же бренду и периоду, а не прирост: клиенты, которые пользуются акцией, отличаются от тех, кто нет. Отменённые, отклонённые, просроченные заказы и заказы с неудачной оплатой здесь не учитываются, но остаются в журнале ниже.',
  'report.log.title': 'Журнал применений',
  'report.log.forPromotion': 'Журнал применений: {code}',
  'report.log.all': 'Показать все акции',
  'report.log.empty': 'Нет применений для этого выбора.',
  'report.log.intro':
    'Новые сверху, не более 200 строк. Отменённый заказ показан со своим статусом. Клиент показан псевдонимом.',
  'report.log.date': 'Применена',
  'report.log.order': 'Заказ',
  'report.log.customer': 'Клиент (псевдоним)',
  'report.log.status': 'Статус заказа',
  'report.log.channel': 'Канал',
  'report.log.who': 'Кто применил',
  'report.log.showCustomer': 'Показать клиента',
  'report.log.openCustomer': 'Открыть карточку клиента',
  'report.log.guestOrder': 'Гостевой заказ: аккаунта клиента нет',
  'report.log.revealDenied': 'У вас нет права просматривать этого клиента.',
  'report.log.revealFailed': 'Не удалось найти клиента.',
  'report.log.revealRetry': 'Повторить',
  'report.log.revealNote':
    'Просмотр клиента записывается в журнал аудита по этому клиенту с указанием, кто смотрел.',
};

const uzLatn: Record<PromotionTextKey, string> = {
  'problem.name': 'Aksiyaga nom bering.',
  'problem.code': 'Kod: 2 dan 64 gacha harf, raqam, defis yoki pastki chiziq.',
  'problem.group': 'Birlashtirish guruhini koʻrsating.',
  'problem.action': 'Kamida bitta amal qoʻshing.',
  'problem.gift': 'Sovgʻa taomni tanlang.',
  'problem.condition': 'Qiymatsiz shartni toʻldiring yoki oʻchiring.',
  title: 'Aksiyalar',
  intro:
    'Shartlar bajarilganda oʻzi qoʻllanadigan avtomatik chegirma va ustamalar. Aksiya qoidalar tekshiruvidan oʻtmaguncha qoralama boʻlib turadi, mehmonlarga chiqishi uchun esa ikkinchi odamning tasdigʻi kerak boʻlishi mumkin. Promokodlar alohida boʻlimda.',
  create: 'Yangi aksiya',
  newTitle: 'Yangi aksiya',
  loading: 'Yuklanmoqda',
  denied: 'Ushbu brend aksiyalariga ruxsat yoʻq',
  empty: 'Hozircha aksiya yaratilmagan.',
  list: 'Aksiyalar birlashtirish guruhlari boʻyicha',
  group: 'Guruh: {name}',
  'list.hint':
    'Guruh ichida mehmon uchun foydaliroq taklif gʻolib boʻladi, ustuvorlik esa faqat teng holatni hal qiladi. Tartibni oʻzgartirish uchun sudrang; tugma tekshirilgan aksiyani yoqadi yoki faol aksiyani oʻchiradi.',
  archived: 'Arxivda ({count})',
  nothingOpen: 'Roʻyxatdan aksiyani oching yoki yangisini yarating.',
  'row.description': '{code} · {status} · {scope}',
  dirty: 'Saqlanmagan oʻzgarishlar bor. Tekshirish yoki ishga tushirishdan oldin saqlang.',
  'kind.DISCOUNT': 'Chegirma',
  'kind.MARKUP': 'Ustama (narxni oshiradi)',
  'scope.ITEM': 'Mos pozitsiyalar',
  'scope.ORDER': 'Butun buyurtma',
  'scope.DELIVERY': 'Yetkazib berish narxi',
  'status.DRAFT': 'Qoralama',
  'status.VALIDATED': 'Tekshirilgan',
  'status.ACTIVE': 'Faol',
  'status.SUSPENDED': 'Toʻxtatilgan',
  'status.ARCHIVED': 'Arxivda',
  'channelType.WEB': 'Veb-sayt',
  'channelType.IOS': 'iOS ilovasi',
  'channelType.ANDROID': 'Android ilovasi',
  'channelType.TELEGRAM': 'Telegram',
  'channelType.KIOSK': 'Kiosk',
  'channelType.QR_TABLE': 'Stoldagi QR',
  'channelType.CALL_CENTRE': 'Aloqa markazi',
  'channelType.POS': 'Kassa',
  'fulfillment.DELIVERY': 'Yetkazib berish',
  'fulfillment.PICKUP': 'Olib ketish',
  'fulfillment.DINE_IN': 'Zalda',
  'action.ITEM_PERCENTAGE_DISCOUNT': 'Mos pozitsiyalarga foizli chegirma',
  'action.ITEM_FIXED_DISCOUNT': 'Har bir mos birlikka belgilangan chegirma',
  'action.ITEM_FIXED_PRICE': 'Birlik uchun belgilangan narx (narxni oshirmaydi)',
  'action.FREE_ITEM': 'Sovgʻa taom',
  'action.ORDER_PERCENTAGE_DISCOUNT': 'Buyurtmaga foizli chegirma',
  'action.ORDER_FIXED_DISCOUNT': 'Buyurtmaga belgilangan chegirma',
  'action.FREE_DELIVERY': 'Bepul yetkazib berish',
  'action.REDUCED_DELIVERY': 'Yetkazib berish narxini kamaytirish',
  'action.ITEM_PERCENTAGE_MARKUP': 'Mos pozitsiyalarga foizli ustama',
  'action.ITEM_FIXED_MARKUP': 'Har bir mos birlikka belgilangan ustama',
  'adjustment.BASE_PRICE': 'Narx',
  'adjustment.MODIFIER': 'Modifikator',
  'adjustment.ITEM_DISCOUNT': 'Pozitsiyaga chegirma',
  'adjustment.ORDER_DISCOUNT': 'Buyurtmaga chegirma',
  'adjustment.FEE': 'Yetkazib berish',
  'adjustment.TAX': 'Soliq',
  'adjustment.ROUNDING': 'Yaxlitlash',
  'adjustment.DELIVERY_FEE_WAIVER': 'Bepul yetkazib berish chegarasi',
  'adjustment.DELIVERY_FEE_BENEFIT': 'Yetkazib berish imtiyozi',
  'adjustment.DELIVERY_TARIFF_DISCOUNT': 'Yetkazib berish tarifi chegirmasi',
  'adjustment.ITEM_MARKUP': 'Pozitsiyaga ustama',
  'verdict.COUPON_NOT_PRESENTED': 'Taqdim etilmagan promokod kerak',
  'verdict.LIMIT_REACHED': 'Qoʻllanish limiti tugagan',
  'verdict.NOT_CLAIMED_AT_PLACEMENT':
    'Buyurtma uni rasmiylashtirishda egallamagan, oʻzgartirish esa egallay olmaydi',
  'verdict.OUTSIDE_WINDOW': 'Amal qilish muddatidan tashqarida',
  'verdict.ZERO_BENEFIT': 'Bu savatda foyda bermaydi',
  'verdict.CURRENCY_MISMATCH': 'Narxlar roʻyxatidan boshqa valyutada',
  'verdict.APPLIED': 'Qoʻllandi: {amount}',
  'verdict.CONDITION_FAILED': '{n}-shart bajarilmadi',
  'verdict.CONDITION_FAILED.any': 'Shart bajarilmadi',
  'verdict.LOST_TO': 'Yutqazdi: {others}',
  'verdict.SUPPRESSED_BY_EXCLUSIVE': 'Eksklyuziv {others} tomonidan chetlatildi',
  'action.validate': 'Qoidalarni tekshirish',
  'action.activate': 'Ishga tushirish',
  'action.suspend': 'Toʻxtatib turish',
  'action.resume': 'Davom ettirish',
  'action.archive': 'Arxivlash',
  'action.close': 'Yopish',
  'dialog.cancel': 'Bekor qilish',
  'activate.title': 'Aksiyani mehmonlar uchun ishga tushiramizmi?',
  'activate.body':
    'Ustama yoki belgilangan chegaradan katta chegirma uchun avval ikkinchi odam tasdigʻi kerak — kerak boʻlsa, sizga aytiladi. Chegaradan past aksiyalar darhol ishga tushadi.',
  'activate.reason': 'Tasdiqlovchi uchun izoh (majburiy emas)',
  'activate.confirm': 'Ishga tushirish',
  'archive.title': 'Aksiyani arxivlaymizmi?',
  'archive.body':
    'U yangi buyurtmalarga qoʻllanmaydi, uni oʻzgartirib yoki qaytarib boʻlmaydi. Allaqachon unga ega buyurtmalarda u saqlanadi, tarixi qoladi.',
  'discard.title': 'Saqlanmagan oʻzgarishlar bekor qilinsinmi?',
  'discard.body': 'Ushbu aksiyadagi oʻzgarishlar saqlanmagan.',
  'discard.confirm': 'Bekor qilish',
  'discard.keep': 'Tahrirlashni davom ettirish',
  'notice.saved': 'Qoralama sifatida saqlandi. Endi qoidalar tekshiruvini ishga tushiring.',
  'notice.validated': 'Qoidalar tekshiruvidan oʻtdi. Ishga tushirish mumkin.',
  'notice.refused': 'Qoidalar tekshiruvidan oʻtmadi. Aksiya qoralama boʻlib qoladi.',
  'notice.activated': 'Aksiya ishga tushdi.',
  'notice.pending': 'Ishga tushirish uchun ikkinchi odam tasdigʻi kutilmoqda.',
  'notice.suspended': 'Aksiya endi yangi buyurtmalarga qoʻllanmaydi.',
  'notice.resumed': 'Aksiya yana amal qilmoqda.',
  'notice.archived': 'Aksiya arxivlandi.',
  'notice.reordered': 'Ustuvorlik tartibi saqlandi.',
  pending:
    '{id} soʻrovi ikkinchi odamni kutmoqda. Qaror «Odamlar → Tasdiqlashlar» boʻlimida qabul qilinadi; qaror chiqqach, «Ishga tushirish»ni yana bosing.',
  'pending.link': 'Tasdiqlashlarni ochish',
  'locked.active':
    'Faol aksiya joyida tahrirlanmaydi. Uni toʻxtatib turing, oʻzgartiring, qoidalar tekshiruvidan oʻtkazing va qayta ishga tushiring.',
  'locked.archived': 'Arxivdagi aksiya tarix hisoblanadi, uni oʻzgartirib boʻlmaydi.',
  'error.toggleNeedsValidation':
    'Faqat tekshirilgan aksiyani yoqish mumkin. Uni oching va avval qoidalar tekshiruvidan oʻtkazing.',
  'error.toggleNotLive': 'Faqat faol aksiyani oʻchirish mumkin.',
  'error.unsaved': 'Avval ochiq aksiyadagi oʻzgarishlarni saqlang yoki bekor qiling.',
  'validation.ok': 'Qoidalar tekshiruvidan oʻtdi.',
  'validation.refused': 'Qoidalar tekshiruvidan oʻtmadi:',
  'issue.place': '{n}-band',
  'issue.NAME_REQUIRED': 'Aksiyaga nom kerak.',
  'issue.CODE_INVALID': 'Kod: 2 dan 64 gacha harf, raqam, defis yoki pastki chiziq.',
  'issue.STACKING_GROUP_REQUIRED': '64 belgidan oshmaydigan birlashtirish guruhi kerak.',
  'issue.CURRENCY_INVALID': 'Valyuta — 3 harfli ISO kodi.',
  'issue.MAXIMUM_INVALID': 'Maksimal chegirma musbat boʻlishi yoki oʻchirilgan boʻlishi kerak.',
  'issue.EXCLUSIVE_WITH_MARKUP': 'Ustama eksklyuziv boʻla olmaydi.',
  'issue.MARKUP_SCOPE_INVALID': 'Ustama pozitsiyalarga tushadi, yetkazib berishga emas.',
  'issue.ORDER_MARKUP_NOT_AVAILABLE':
    'Butun buyurtmaga ustama (xizmat haqi) hozircha mavjud emas; faqat pozitsiyalarga ustama yaratish mumkin.',
  'issue.MARKUP_NOT_COUPON_GATED': 'Ustama promokod talab qila olmaydi.',
  'issue.NO_ACTION': 'Kamida bitta amal qoʻshing.',
  'issue.ACTION_SCOPE_MISMATCH': 'Bu amal aksiya turi va doirasiga mos kelmaydi.',
  'issue.OPERAND_INVALID': 'Qiymat kiritilmagan yoki ruxsat etilgan oraliqdan tashqarida.',
  'issue.PERCENTAGE_OVER_100': 'Foiz 100 dan oshmasligi kerak.',
  'issue.FREE_ITEM_UNBOUNDED':
    'Sovgʻa uchun kamida 1 miqdor kerak: cheksiz sovgʻa butun savatni berib yuboradi.',
  'issue.UNKNOWN_REFERENCE': 'Bu brendga tegishli boʻlmagan narsa koʻrsatilgan.',
  'issue.NO_PRICED_VARIANT_MATCH':
    'Koʻrsatilgan taomlarning hech birida amaldagi narx yoʻq, aksiya hech qachon ishlamaydi.',
  'issue.WEEKDAYS_EMPTY': 'Kamida bitta hafta kunini tanlang.',
  'issue.WINDOW_INVERTED':
    'Davr boshlanishidan keyin tugashi kerak va bir daqiqada boshlanib tugay olmaydi.',
  'issue.SEQUENCE_NEEDS_CUSTOMER_LIMIT':
    'Birinchi yoki N-buyurtma aksiyasi har bir mijozni bitta qoʻllash bilan cheklashi kerak: aynan shu ikki tez buyurtmaning ikkalasi ham birinchi boʻlishiga yoʻl qoʻymaydi.',
  'issue.LIMIT_ON_COUPON_PROMOTION':
    'Promokodli aksiyaning limitlari promokodning oʻzida belgilanadi, bu yerda emas.',
  'issue.STACKING_GROUP_MIXES_SCOPES':
    'Pozitsiyalar aksiyasi buyurtma yoki yetkazib berish aksiyasi bilan bitta guruhda boʻla olmaydi; boshqa guruh tanlang.',
  'issue.CURRENCY_MISMATCH':
    'Aksiya valyutasi brendning narxlar roʻyxati valyutasidan farq qiladi.',
  'issue.UNCAPPED_PERCENTAGE':
    'Maksimumsiz foizli chegirma har qanday savatdan, qanchalik katta boʻlmasin, ulush oladi.',
  'pane.rule': 'Qoida',
  'pane.simulate': 'Simulyator',
  'pane.history': 'Versiyalar',
  'pane.redemptions': 'Qoʻllanishlar',
  'history.intro':
    'Har bir tekshiruv, ishga tushirish va ustuvorlik oʻzgarishi qoidani dvigatel oʻqigan holda aynan qayd etadi; yangilari tepada. Eski chek uni hisoblagan versiya bilan izohlanadi.',
  'history.empty': 'Hozircha versiya yoʻq: aksiya qoidalar tekshiruvida qayd etiladi.',
  'history.version': 'Versiya',
  'history.reason': 'Sabab',
  'history.by': 'Kim',
  'history.when': 'Qachon',
  'history.activated': 'Ishga tushirgan: {by}, {when}.',
  'redemptions.loading': 'Qoʻllanishlar yuklanmoqda',
  'redemptions.empty': 'Bu aksiya hali qoʻllanmagan.',
  'redemptions.error': 'Qoʻllanishlarni yuklab boʻlmadi.',
  'redemptions.intro':
    'Har bir buyurtma uchun bitta qator, yangilari tepada, 200 tagacha. Oʻzgartirilgan buyurtma yangi qator qoʻshmaydi, oʻz qatorini yangilaydi. Faqat identifikatorlar: bu yerda ism va aloqa maʻlumotlari yoʻq.',
  'redemptions.order': 'Buyurtma',
  'redemptions.version': 'Versiya',
  'redemptions.discount': 'Chegirma',
  'redemptions.markup': 'Ustama',
  'redemptions.status': 'Holat',
  'editor.basics': 'Asosiy',
  'editor.name': 'Nomi (ichki, roʻyxat va hisobotlar uchun)',
  'editor.code': 'Aksiya kodi',
  'editor.code.hint':
    'Brend ichida noyob: 2 dan 64 gacha harf, raqam, defis yoki pastki chiziq. Mehmonlar uni koʻrmaydi.',
  'editor.kind': 'Turi',
  'editor.scope': 'Qoʻllanadi',
  'editor.currency': 'Valyuta',
  'editor.markupNote':
    'Ustama mos pozitsiyalar narxini har qanday chegirmadan oldin oshiradi va doim ikkinchi odam tasdigʻini talab qiladi. Butun buyurtmaga xizmat haqi hozircha mavjud emas.',
  'editor.group': 'Birlashtirish guruhi',
  'editor.group.hint':
    'Guruh ichida mehmon uchun foydaliroq taklif gʻolib boʻladi; turli guruhlar qoʻshiladi. Pozitsiyalar aksiyasi buyurtma yoki yetkazib berish aksiyasi bilan bitta guruhda boʻla olmaydi.',
  'editor.exclusive': 'Eksklyuziv',
  'editor.exclusive.hint':
    'Eksklyuziv aksiya xuddi boshqa chegirmalar yoʻqdek hisoblanadi; mehmon uni va boshqalarning eng yaxshi kombinatsiyasidan kattasini oladi. Promokod doim eksklyuziv.',
  'editor.window': 'Amal qilish muddati',
  'editor.validFrom': 'Boshlanishi',
  'editor.validUntil': 'Tugashi',
  'editor.window.hint':
    'Boʻsh qoldirsangiz — «ishga tushgandan» va «muddatsiz». Vaqt shu qurilmaning vaqt mintaqasida; «kun vaqti» sharti filial vaqti boʻyicha hisoblanadi.',
  'editor.conditions': 'Shartlar',
  'editor.conditions.hint':
    'Barcha shartlar bajarilishi kerak; shart boʻlmasa, aksiya har qanday buyurtmaga qoʻllanadi. «Yoki» yoʻq: «yoki-yoki» uchun bitta guruhda ikkita aksiya yarating.',
  'editor.menuBranch': 'Taomlar roʻyxati filial menyusidan',
  'editor.menuLoading': 'Menyu yuklanmoqda',
  'editor.actions': 'Nima qiladi',
  'editor.actionType': 'Amal',
  'editor.addAction': 'Amal qoʻshish',
  'editor.removeAction': 'Bu amalni oʻchirish',
  'editor.percent': 'Foiz',
  'editor.amount': 'Summa',
  'editor.unitPrice': 'Birlikning yangi narxi',
  'editor.reduceBy': 'Narxni kamaytirish',
  'editor.reduceBy.PERCENT': 'Foiz',
  'editor.reduceBy.AMOUNT': 'Belgilangan summa',
  'editor.gift': 'Sovgʻa taomlar',
  'editor.giftQuantity': 'Bepul birliklar, koʻpi bilan',
  'editor.giftMode': 'Qanchalik tez-tez',
  'editor.giftMode.ONCE': 'Buyurtmaga bir marta',
  'editor.giftMode.PER_MULTIPLE': 'Har n ta mos birlik uchun',
  'editor.giftTrigger': 'Bitta sovgʻa birligi uchun mos birliklar',
  'editor.gift.hint':
    'Sovgʻa butun savat boʻyicha cheklangan, taom nechta qatorda turmasin; narxlash savatda yoʻq qatorni hech qachon qoʻshmaydi.',
  'editor.limits': 'Chegara va limitlar',
  'editor.hasCap': 'Maksimal chegirmani cheklash',
  'editor.cap': 'Maksimal chegirma',
  'editor.hasTotalLimit': 'Umumiy qoʻllanishlar sonini cheklash',
  'editor.totalLimit': 'Jami qoʻllanishlar',
  'editor.hasCustomerLimit': 'Mijoz uchun qoʻllanishlarni cheklash',
  'editor.customerLimit': 'Mijoz uchun qoʻllanishlar',
  'editor.limits.hint':
    'Buyurtma bekor qilinsa, oʻrin qaytarilmaydi. Mehmon savatida hisoblash uchun mijoz yoʻq, shuning uchun mijoz limiti mehmonlarga taalluqli emas.',
  'editor.loyalty': 'Sodiqlik ballari',
  'editor.loyaltyAccrual': 'Ushbu aksiyali buyurtma uchun ballar',
  'editor.loyaltyRedemption': 'Bunday buyurtmada ballarni sarflash',
  'loyalty.accrual.ACCRUE': 'Odatdagidek hisoblash',
  'loyalty.accrual.SUPPRESS': 'Hisoblamaslik',
  'loyalty.redemption.ALLOW': 'Ruxsat etilgan',
  'loyalty.redemption.BLOCK': 'Taqiqlangan',
  'editor.unsupported':
    'Bu aksiyada konsol koʻrsata olmaydigan qoidalar bor ({types}). Hech narsa yoʻqolmasligi uchun u faqat oʻqish uchun ochilgan; uni API orqali oʻzgartiring yoki arxivlab, yangisini yarating.',
  'editor.save': 'Qoralama sifatida saqlash',
  'editor.saving': 'Saqlanmoqda…',
  'editor.cancel': 'Bekor qilish',
  'sim.title': 'Simulyator',
  'sim.intro':
    'Oʻylab topilgan savatni haqiqiy dvigatel bilan hisoblaydi va brenddagi har bir aksiya qoʻllanganmi yoki nega yoʻqligini koʻrsatadi. Hech narsa saqlanmaydi: na hisob-kitob, na qoʻllanish, na hisoblagich.',
  'sim.branch': 'Filial',
  'sim.channel': 'Savdo kanali',
  'sim.mode': 'Buyurtma turi',
  'sim.payment': 'Toʻlov usuli',
  'sim.instant': 'Xizmat vaqti (boʻsh — hozir)',
  'sim.coupon': 'Promokod (majburiy emas)',
  'sim.latitude': 'Yetkazib berish kengligi',
  'sim.longitude': 'Yetkazib berish uzunligi',
  'sim.destination.hint':
    'Nuqtasiz yetkazib berish narxi va hududi aniqlanmaydi, shuning uchun hudud sharti bajarilmaydi.',
  'sim.customer': 'Mijoz faktlar koʻrinishida',
  'sim.customer.hint':
    'Akkaunt emas: faqat bu buyurtma tarixda nechanchi boʻlishi va mijoz qaysi auditoriyalarda ekanligi.',
  'sim.brandPosition': 'Bu ularning brenddagi buyurtma raqami boʻlardi',
  'sim.channelPosition': '…va shu kanal orqali buyurtma raqami',
  'sim.cart': 'Savat',
  'sim.addDish': 'Taom qoʻshing: nomini yozishni boshlang',
  'sim.cart.empty': 'Kamida bitta taom qoʻshing.',
  'sim.quantity': 'Miqdor',
  'sim.removeLine': 'Bu qatorni oʻchirish',
  'sim.try': 'Boshqasini sinab koʻrish',
  'sim.useCandidate': 'Tahrirlanayotgan aksiyani hozirgi holida hisobga olish (saqlanmagan)',
  'sim.replay': '{code} qoidasi versiyasi',
  'sim.replay.current': 'Joriy',
  'sim.replay.version': '{version}-versiya',
  'sim.run': 'Savatni hisoblash',
  'sim.running': 'Hisoblanmoqda…',
  'sim.subtotal': 'Oraliq jami',
  'sim.discount': 'Chegirma',
  'sim.fee': 'Yetkazib berish',
  'sim.tax': 'Soliq',
  'sim.total': 'Jami',
  'sim.inputs': '{instant} ({zone}) uchun hisoblandi, buyurtma turi: {mode}.',
  'sim.noAccrual': 'Qoʻllangan aksiya bu buyurtmada ballar hisoblanishini oʻchiradi.',
  'sim.noRedemption': 'Qoʻllangan aksiya bu buyurtmada ballarni sarflashni taqiqlaydi.',
  'sim.adjustments': 'Jami qanday shakllandi',
  'sim.trace': 'Brenddagi barcha aksiyalar va ularga nima boʻlgani',
  'report.intro':
    'Har bir avtomatik aksiya va promokod qancha chegirma berdi va qancha daromad keltirdi — kun yopilganda shakllanadigan qoʻllanish faktlari asosida. Oxirgi bir-ikki ish kuni hali hisoblanayotgan boʻlishi mumkin.',
  'report.loading': 'Yuklanmoqda…',
  'report.empty': 'Bu davrda birorta aksiya qoʻllanmagan.',
  'report.column.promotion': 'Aksiya',
  'report.column.source': 'Manba',
  'report.column.redemptions': 'Qoʻllanishlar',
  'report.column.customers': 'Noyob mijozlar',
  'report.column.discount': 'Berilgan chegirma',
  'report.column.markup': 'Ustama',
  'report.column.revenue': 'Aksiyali daromad',
  'report.column.checkWith': 'Aksiyali oʻrtacha chek',
  'report.column.checkWithout': 'Aksiyasiz oʻrtacha chek',
  'report.source.AUTOMATIC': 'Avtomatik',
  'report.source.COUPON': 'Promokod',
  'report.source.GRANT': 'Shaxsiy imtiyoz',
  'report.status.none': 'Hali yopilmagan',
  'report.comparison':
    'Ikkita oʻrtacha chek bir xil brend va davr boʻyicha taqqoslash, oʻsish emas: aksiyadan foydalanadigan mijozlar foydalanmaydiganlardan farq qiladi. Bekor qilingan, rad etilgan, muddati oʻtgan va toʻlovi amalga oshmagan buyurtmalar bu yerda hisobga olinmaydi, quyidagi jurnalda qoladi.',
  'report.log.title': 'Qoʻllanishlar jurnali',
  'report.log.forPromotion': '{code} qoʻllanishlar jurnali',
  'report.log.all': 'Barcha aksiyalarni koʻrsatish',
  'report.log.empty': 'Bu tanlov uchun qoʻllanishlar yoʻq.',
  'report.log.intro':
    'Yangilari tepada, 200 qatorgacha. Bekor qilingan buyurtma oʻz holati bilan koʻrsatiladi. Mijoz taxallus bilan koʻrsatiladi.',
  'report.log.date': 'Qoʻllangan',
  'report.log.order': 'Buyurtma',
  'report.log.customer': 'Mijoz (taxallus)',
  'report.log.status': 'Buyurtma holati',
  'report.log.channel': 'Kanal',
  'report.log.who': 'Kim qoʻllagan',
  'report.log.showCustomer': 'Mijozni koʻrsatish',
  'report.log.openCustomer': 'Mijoz kartasini ochish',
  'report.log.guestOrder': 'Mehmon buyurtmasi: mijoz hisobi yoʻq',
  'report.log.revealDenied': 'Bu mijozni koʻrishga ruxsatingiz yoʻq.',
  'report.log.revealFailed': 'Mijozni topib boʻlmadi.',
  'report.log.revealRetry': 'Qayta urinish',
  'report.log.revealNote':
    'Mijozni koʻrish audit jurnaliga shu mijoz boʻyicha, kim koʻrgani bilan yoziladi.',
};

export const PROMOTION_TEXTS: Readonly<Record<Locale, Readonly<Record<PromotionTextKey, string>>>> =
  {
    en,
    ru,
    'uz-Latn': uzLatn,
  };

/** One promotion string in `locale`, with `{placeholder}` values interpolated. */
export function promotionText(
  locale: Locale,
  key: PromotionTextKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  return interpolate(PROMOTION_TEXTS[locale][key], values);
}

/**
 * `{{ 'editor.name' | pt }}`: `t` for this feature's own table. Impure for the same
 * reason `t` is (the text depends on the locale signal, not only on the key), and
 * typed on {@link PromotionTextKey} so a typo in a template is a build error.
 */
@Pipe({ name: 'pt', pure: false })
export class PromotionTextPipe implements PipeTransform {
  private readonly i18n = inject(I18n);

  transform(key: PromotionTextKey, values?: Readonly<Record<string, string | number>>): string {
    return promotionText(this.i18n.locale(), key, values);
  }
}
