// GENERATED OUTPUT — NOT AUTHORED. Do not edit this file by hand.
//
// Source of record: the HorecaOS Design System token sheet, vendored into this
// repository from `frontend/prototypes/control-plane/src/tokens.css` in the
// qoida-platform repository (identical to the operations prototype's copy).
// Geometry values come from ADR 0035, "The MOBILE skin, restated in Flutter".
//
// ADR 0035's implementation checklist names a `sync-tokens` tool in the
// platform repository that will regenerate this file and a drift check that
// fails CI on a hand edit. Neither exists yet. Until they do, this file was
// transcribed by hand from the sheet above and
// test/design/token_drift_test.dart is the only guard. That is a weaker
// guarantee than the header claims, and it is stated here rather than
// discovered later.
//
// The four applications vendor their own copies because there is no shared
// package registry yet; see README, "Why the tokens are vendored".

import 'dart:ui' show Color;

/// The HorecaOS palette, MOBILE skin.
///
/// Colour reaches a widget through `Theme.of(context).extension<HorecaOSTokens>()`
/// (see `horecaos_theme.dart`), never by importing this class at a call site and
/// never through `Colors.*`. These constants exist so the theme has something
/// to be built from.
abstract final class HorecaOSPalette {
  /// Platform blue. Links, primary actions, focus, selection. Never decoration.
  static const Color primary = Color(0xFF0F62FE);
  static const Color primaryHover = Color(0xFF0050E6);
  static const Color primaryActive = Color(0xFF002D9C);

  static const Color ink = Color(0xFF161616);
  static const Color inkMuted = Color(0xFF525252);
  static const Color inkSubtle = Color(0xFF8C8C8C);

  static const Color canvas = Color(0xFFFFFFFF);
  static const Color surface1 = Color(0xFFF4F4F4);
  static const Color surface2 = Color(0xFFE0E0E0);
  static const Color hairline = Color(0xFFE0E0E0);

  static const Color inverse = Color(0xFF161616);
  static const Color inverseInk = Color(0xFFFFFFFF);
  static const Color inverseInkMuted = Color(0xFFC6C6C6);

  static const Color success = Color(0xFF24A148);

  /// Dot only. Never text on white — pair it with [warningText].
  static const Color warning = Color(0xFFF1C21B);
  static const Color error = Color(0xFFDA1E28);

  static const Color infoTint = Color(0xFFEDF5FF);
  static const Color infoText = Color(0xFF0043CE);
  static const Color successTint = Color(0xFFDEFBE6);
  static const Color successText = Color(0xFF0E6027);
  static const Color warningTint = Color(0xFFFCF4D6);
  static const Color warningText = Color(0xFF8E6A00);
  static const Color errorTint = Color(0xFFFFF1F1);
  static const Color errorText = Color(0xFFA2191F);
}

/// Geometry, motion and hit targets for the MOBILE skin.
///
/// MOBILE inherits FIELD's geometry, not CONSOLE's. The 0px corner that is the
/// brand on a dense console is wrong under a thumb, and ADR 0035 says so
/// explicitly: 8dp radii from the FIELD `--q-radius`, 48dp minimum targets.
abstract final class HorecaOSGeometry {
  /// FIELD radius. CONSOLE's is 0; MOBILE is not CONSOLE.
  static const double radius = 8;

  /// Minimum interactive target. Material's default is 48 and iOS's guidance is
  /// 44; the larger number is used on both platforms so one codebase does not
  /// render as two products.
  static const double minTarget = 48;

  static const double hairline = 1;

  static const double spaceXs = 4;
  static const double spaceSm = 8;
  static const double spaceMd = 16;
  static const double spaceLg = 24;
  static const double spaceXl = 32;
}

/// Motion. Only `transform` and `opacity` animate; nothing here animates colour.
abstract final class HorecaOSMotion {
  static const Duration fast = Duration(milliseconds: 110);
  static const Duration base = Duration(milliseconds: 150);

  /// The `--q-ease-productive` cubic bezier, as its four control values.
  /// Turned into a `Curve` in `horecaos_theme.dart` so this file stays free of
  /// Flutter imports and can be regenerated by a tool that knows nothing about
  /// Flutter.
  static const List<double> easeProductive = <double>[0.2, 0, 0.38, 0.9];
}

/// The one shadow this system has.
///
/// CONSOLE has no shadows at all; FIELD and MOBILE have exactly one, and it is
/// not a scale. Material 3's tonal elevation — which recolours a surface by
/// depth — is switched off in `horecaos_theme.dart` because this design system
/// does not express depth as colour.
abstract final class HorecaOSElevation {
  static const Color shadowColor = Color(0x1F161616);
  static const double blurRadius = 12;
  static const double yOffset = 2;
}
