// GENERATED OUTPUT — NOT AUTHORED. Do not edit this file by hand.
//
// Source of record: the closed type scale in the Qoida Design System token
// sheet (`--q-display` through `--q-caption` and `.q-data-lg`), vendored from
// `frontend/prototypes/control-plane/src/tokens.css`.
//
// CSS `line-height` is unitless there; Flutter's `TextStyle.height` is the same
// multiple, so the numbers carry across unchanged. CSS `letter-spacing` is in
// px and Flutter's is in logical pixels, which also carries across.

import 'package:flutter/widgets.dart';

/// The closed type scale.
///
/// Every size in the application is one of these. A `TextStyle` constructed at
/// a call site is a design-system violation exactly as an inline `font-size` is
/// on web, and test/design/design_system_lint_test.dart fails the build on one.
abstract final class QoidaTypography {
  /// IBM Plex Sans, once the faces are bundled.
  ///
  /// Null today, and deliberately so. ADR 0035 requires the font bundled as an
  /// application asset rather than fetched — ru and uz-Latn need the Cyrillic
  /// and Latin Extended subsets present offline, and a font that arrives over
  /// the network arrives after first paint. The `.ttf` files are not in this
  /// repository (see assets/fonts/README.md). Naming a family that is not
  /// bundled makes Flutter fall back at runtime with a console error on every
  /// frame, so the name is withheld until the files land. Setting this to
  /// `'IBMPlexSans'` and uncommenting the pubspec `fonts:` block are one
  /// commit, and nothing else changes.
  static const String? fontFamily = null;

  /// `.q-display` — 42/300, 1.20, -0.02em.
  static const TextStyle display = TextStyle(
    fontFamily: fontFamily,
    fontSize: 42,
    fontWeight: FontWeight.w300,
    height: 1.20,
    letterSpacing: -0.84, // -0.02em at 42px
  );

  /// `.q-headline` — 32/400, 1.25.
  static const TextStyle headline = TextStyle(
    fontFamily: fontFamily,
    fontSize: 32,
    fontWeight: FontWeight.w400,
    height: 1.25,
  );

  /// `.q-title` — 24/400, 1.33.
  static const TextStyle title = TextStyle(
    fontFamily: fontFamily,
    fontSize: 24,
    fontWeight: FontWeight.w400,
    height: 1.33,
  );

  /// `.q-subhead` — 20/400, 1.40.
  static const TextStyle subhead = TextStyle(
    fontFamily: fontFamily,
    fontSize: 20,
    fontWeight: FontWeight.w400,
    height: 1.40,
  );

  /// `.q-body` — 16/400, 1.50, 0.16px.
  static const TextStyle body = TextStyle(
    fontFamily: fontFamily,
    fontSize: 16,
    fontWeight: FontWeight.w400,
    height: 1.50,
    letterSpacing: 0.16,
  );

  /// `.q-body-sm` — 14/400, 1.29, 0.16px.
  static const TextStyle bodySmall = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.29,
    letterSpacing: 0.16,
  );

  /// `.q-emphasis` — 14/600, 1.29, 0.16px.
  static const TextStyle emphasis = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    fontWeight: FontWeight.w600,
    height: 1.29,
    letterSpacing: 0.16,
  );

  /// `.q-caption` — 12/400, 1.33, 0.32px.
  static const TextStyle caption = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.33,
    letterSpacing: 0.32,
  );

  /// `.q-data-lg` — 28/300, 1.20, tabular figures.
  ///
  /// Tabular because it renders money and counts. Proportional digits make a
  /// column of totals ripple as it updates.
  static const TextStyle dataLarge = TextStyle(
    fontFamily: fontFamily,
    fontSize: 28,
    fontWeight: FontWeight.w300,
    height: 1.20,
    fontFeatures: <FontFeature>[FontFeature.tabularFigures()],
  );

  /// `.q-tnum` — the tabular-figures modifier, applied to any scale entry that
  /// happens to be showing a number.
  static const List<FontFeature> tabular = <FontFeature>[
    FontFeature.tabularFigures(),
  ];

  /// The lower and upper bound on `MediaQuery.textScaler`.
  ///
  /// Dynamic type is honoured — refusing it is an accessibility failure — but a
  /// closed scale does not survive a 200 % system setting: a 42px display style
  /// at 2.0 pushes every price off the row. Clamping keeps the scale legible at
  /// both ends. The upper bound is a judgement, not a token, and is the first
  /// thing to revisit with a real accessibility budget (ADR 0035 lists that
  /// budget as an open input).
  static const double minTextScale = 0.85;
  static const double maxTextScale = 1.5;

  /// Applies the bounds above.
  ///
  /// A named function rather than a `clamp` call inlined into the widget tree,
  /// so the rule can be asserted without pumping a widget and without depending
  /// on which layer of the framework happens to own `MediaQuery` this release.
  static TextScaler clampScaler(TextScaler scaler) => scaler.clamp(
    minScaleFactor: minTextScale,
    maxScaleFactor: maxTextScale,
  );
}
