/**
 * Idempotency keys (ADR 0031).
 *
 * Every non-GET call to the platform carries an `Idempotency-Key`. The whole
 * value of the mechanism rests on one property that is easy to get wrong: **the
 * key must be minted once per intent and reused on every retry of that intent**.
 * A key generated inside the retry loop makes each retry a new intent, which is
 * how a double-tapped "approve" becomes two approvals — precisely the thing the
 * header exists to prevent.
 *
 * So keys are not generated by the API client. They are generated when an
 * operator expresses an intent, and handed to the client, and the type below
 * exists to make an anonymous string impossible to pass by accident.
 */

declare const idempotencyKeyBrand: unique symbol;

/** A key minted for one operator intent. Branded so it cannot be conjured from a string. */
export type IdempotencyKey = string & { readonly [idempotencyKeyBrand]: true };

/**
 * Mints a key for one intent.
 *
 * `crypto.randomUUID` is a browser built-in in every target this console
 * supports and needs no dependency. It requires a secure context, which the
 * console has: it is served over HTTPS in production and over `localhost` in
 * development, both of which qualify.
 */
export function newIdempotencyKey(): IdempotencyKey {
  return crypto.randomUUID() as IdempotencyKey;
}

/**
 * One operator intent, retryable without duplicating its effect.
 *
 * Hold this — not the key — for the lifetime of a command. When a submission
 * fails with a retryable error, resubmit the same `Command` and the same key
 * goes out again; the server replays its stored response with
 * `Idempotency-Replayed: true` if the first attempt actually landed.
 *
 * When the operator changes what they are asking for, that is a new intent and
 * needs a new command. Reusing a key with a different body is a 409
 * IDEMPOTENCY_KEY_REUSED, which is the server correctly refusing to guess.
 */
export interface Command<TBody> {
  readonly key: IdempotencyKey;
  readonly body: TBody;
}

export function command<TBody>(body: TBody): Command<TBody> {
  return { key: newIdempotencyKey(), body };
}

/** True when the server replayed a stored response rather than acting again. */
export function wasReplayed(headers: { get(name: string): string | null }): boolean {
  return headers.get('Idempotency-Replayed') === 'true';
}
